### ISSUE TITLE
Memory leak in WebSocketImpl.outQueue

### ISSUE THREAD

**Issue by martin-g** [TooTallNate/Java-WebSocket#773] opened 2018-09-11 08:39 UTC
Hi,

This is not a bug report or feature request but actually I'd like to ask for help debugging a possible memory leak.

In the following screenshot you can see that ~51% of the used heap is kept by WebSocketWorker and WebSocketImpl.

![51-percents-in-websocketserver](https://user-images.githubusercontent.com/232002/45348398-32292500-b5b7-11e8-999b-35d337c871be.png)

And here we see that actually `WebSocketImpl#outQueue` (with hashcode `0x7127e8b30`) is the one keeping the memory. 
![outqueue](https://user-images.githubusercontent.com/232002/45347350-84b51200-b5b4-11e8-8a8e-2b44c2ec4639.png)

Its size is 25320:
![queue-size-25320](https://user-images.githubusercontent.com/232002/45347507-f0977a80-b5b4-11e8-887b-a75c90537e0a.png)

Debugging the code I've seen that `outQueue` is populated when I use `org.java_websocket.WebSocket#send(java.lang.String)` method. At that time there is a check whether the connection is still opened and `WebsocketNotConnectedException` is being thrown in case it is not. Then `org.java_websocket.WebSocketImpl#write(java.nio.ByteBuffer)` is called where there the `buf` is just put into `outQueue`. 
Later in the run loop of `org.java_websocket.server.WebSocketServer#run()` the `outQueue` must be drained and actually sent to the client. In case of an error an IOException is thrown and `org.java_websocket.server.WebSocketServer#onClose(WebSocket, int, String, boolean)` callback is called.

One thing that I notice is that neither `org.java_websocket.server.WebSocketServer#handleIOException()` nor `org.java_websocket.WebSocketImpl#closeConnection(int, java.lang.String, boolean)` clear the contents of `inQueue` and `outQueue`. But I am not sure whether this is the reason for the huge out queues I have in the heap dump.

Do you have an idea what could be the problem and what I could do to debug more ?

I use version 1.3.8. I see that 1.3.9 is released and I will upgrade to it but I do not see anything that might fix it in the changelog.

For the heap analysis I use Eclipse Memory Analyzer (v 1.8.0).

Thank you!

**Comment by marci4** [comment] 2018-09-12 05:37
Hello @martin-g,

thank you for your bug report!

Running everything with the profiler, I saw some left over references to `WebSocketImpl` instances.

The problem is in my eyes, that the WebSocketWorker is referencing an instance but will still keep it until a new WebSocketImpl instance is put into the queue and therefore gc cannot clean up everything.

I attached a patched version. Could you please check if this solves the issue. If not I may need additional steps to repeat!
[Java-WebSocket-1.3.10-SNAPSHOT.zip](https://github.com/TooTallNate/Java-WebSocket/files/2373675/Java-WebSocket-1.3.10-SNAPSHOT.zip)

Best regards,
marci4

**Comment by martin-g** [comment] 2018-09-12 06:57
Thank you, @marci4 !
I will test it soon!

Could you please push your changes in a branch so I can see them ?

**Comment by marci4** [comment] 2018-09-12 07:05
Hello @martin-g,

you can find it [here](https://github.com/marci4/Java-WebSocket-Dev/tree/Issue773). Just merged it locally back to 1.3.9.

Best regards,
marci4

**Comment by marci4** [comment] 2018-09-21 16:48
@martin-g any news?

**Comment by martin-g** [comment] 2018-09-25 07:11
I will take some heap dumps and take a look later today!

**Comment by martin-g** [comment] 2018-09-25 11:58
Hi @marci4,

Everything looks in today's heap dump!
Thank you!

**Closed** 2018-09-25 20:33 UTC
Labels: Bug, Server
