### ISSUE TITLE
Connection timeout for different IP range

### ISSUE THREAD

**Issue by PemmasaniRajesh** [TooTallNate/Java-WebSocket#1198] opened 2021-11-17 13:35 UTC
When I'm trying to connect a websocket with different IP range address, connection timeout is almost 120 secs.

For example, client ip address is 192.168.1.100 and server ip address is 192.168.139.100 then the connections timeout is 120 secs.

If client ip address is 192.168.1.100 and server ip address is 192.168.1.101 then the connections timeout is less than 5 secs.

Is it normal behaviour, or is there any way to achieve the connection timeout in less than 5 secs.

**Comment by PhilipRoman** [comment] 2021-11-17 15:46
Hello! Please post the library version you use and debug logs (see https://github.com/TooTallNate/Java-WebSocket/wiki/SimpleLogger-example) or code that reproduces the problem. Without this information we cannot help.

**Comment by PemmasaniRajesh** [comment] 2021-11-17 16:11
I'm using the below library version: 

implementation "org.java-websocket:Java-WebSocket:1.5.1"

Below is the code I'm using for connecting the webSocket, It's in Kotlin:

`mWebSocketClient = object : WebSocketClient(uri) {

            override fun onOpen(serverHandshake: ServerHandshake) {
                mWebSocketClient!!.send("TempRecordTime,$tempRecordTime")
                tempViewModel.setStatus(Global.SOCKET_OPEN)
                Log.i(TAG, "onOpen")
            }

            override fun onMessage(s: String) {
                activity?.runOnUiThread {
                    Log.i(TAG, "onMessage" + s)
                   // tempViewModel.setTemp(s.toFloat())
                    recordedTempList.add(s.toFloat())
                    if (recordedTempList.size == 1) {
                        timer.start()
                        start_time = System.currentTimeMillis()
                    }
                }
            }

            override fun onClose(i: Int, s: String, b: Boolean) {
                Log.i(TAG, "Socket Connection Closed " + s)
                tempViewModel.setStatus(Global.SOCKET_CLOSED)
            }

            override fun onError(e: Exception) {
                Log.i(TAG, "Socket Connection Error " + e.message)
                tempViewModel.setStatus(Global.SOCKET_ERROR)
                /*when socket is unreachable....*/
                Handler(Looper.getMainLooper()).postDelayed({
                    Log.i(TAG, "Socket Connection Error inside handler$isTempValidated")
                    if(!this@TemperatureDialogFragment.isTempValidated){
                        listener?.tempStatus("Error in connecting to temperature sensor")
                        if(dialog!=null && dialog!!.isShowing){
                            dismiss()
                        }
                    }
                },2000)
            }

            override fun onCloseInitiated(code: Int, reason: String?) {
                super.onCloseInitiated(code, reason)
            }

            override fun onClosing(code: Int, reason: String?, remote: Boolean) {
                super.onClosing(code, reason, remote)
            }

            override fun closeConnection(code: Int, message: String?) {
                super.closeConnection(code, message)
            }

            override fun onWebsocketPing(conn: WebSocket?, f: Framedata?) {
                super.onWebsocketPing(conn, f)
            }

            override fun onWebsocketPong(conn: WebSocket?, f: Framedata?) {
                super.onWebsocketPong(conn, f)
            }

            override fun onWebsocketHandshakeSentAsClient(
                conn: WebSocket?,
                request: ClientHandshake?
            ) {
                super.onWebsocketHandshakeSentAsClient(conn, request)
            }

            override fun onWebsocketHandshakeReceivedAsClient(
                conn: WebSocket?,
                request: ClientHandshake?,
                response: ServerHandshake?
            ) {
                super.onWebsocketHandshakeReceivedAsClient(conn, request, response)
            }
        }

        (mWebSocketClient as WebSocketClient).connect()`

**Comment by marci4** [comment] 2021-12-27 16:26
Cannot reproduce it here. Maybe a router thing?

**Comment by marci4** [comment] 2022-05-08 19:37
Still cannot reproduce and no update. 

Closing dead issue

**Closed by marci4** 2022-05-08 19:37 UTC
Labels: needs-investigation
