### ISSUE TITLE
websocket version 1.4.0 often reports the following exception on android7.0 devices

### ISSUE THREAD

**Issue by baocui** [TooTallNate/Java-WebSocket#871] opened 2019-04-03 02:33 UTC
websocket version 1.4.0 often reports the following exception on android7.0 devices

 org.java_websocket.exceptions.InvalidFrameException: bad rsv RSV1: false RSV2: true RSV3: true
        at org.java_websocket.extensions.DefaultExtension.isFrameValid(DefaultExtension.java:64)
        at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:507)
        at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:648)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:378)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:425)
        at java.lang.Thread.run(Thread.java:761)

**Comment by marci4** [comment] 2019-04-03 02:58
Hello @baocui,

Please provide an example application with some steps to repeat.

Best regards,
Marcel

**Comment by marci4** [comment] 2019-04-08 19:04
Any update?

**Comment by marci4** [comment] 2019-04-14 16:58
Closing this issue as cannot reproduce due to missing information!

Best regards,
Marcel

**Closed by marci4** 2019-04-14 16:58 UTC
Labels: Android, Unclear, missing-information
