### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Gurmail89** [TooTallNate/Java-WebSocket#950] opened 2019-12-04 05:58 UTC
We're getting connection timeout on Android devices for specific networks

On WebSocket Error:java.net.ConnectException: failed to connect to api.chat.com/2600:1f14:c6f:b001:cef6:15bd:ef49:28d1 (port 3002) from /:: (port 54802): connect failed: ETIMEDOUT (Connection timed out).

Please suggest us how to fix this

Thanks,

**Comment by marci4** [comment] 2020-01-03 15:29
Please provide additional informations and steps to reproduce!

**Comment by marci4** [comment] 2020-01-20 19:41
Closing this issue as cannot reproduce!

**Closed by marci4** 2020-01-20 19:41 UTC
Labels: cannot-reproduce, missing-information
