### ISSUE TITLE
Setting handshake timeout Websocket client

### ISSUE THREAD

**Issue by FahrihFatahilah** [TooTallNate/Java-WebSocket#1363] opened 2023-10-06 07:49 UTC
i create a stresstest tool for websocket, somehow from server did not send any handshake ,
from 10 connection i only receive 8 handshake
is possible to setting client handshake timeout with websocket server from springboot

thank you so much !

**Comment by PhilipRoman** [comment] 2023-10-06 10:06
To clarify, you are using this library as a client and spring boot as a server?

**Comment by FahrihFatahilah** [comment] 2023-10-08 13:01
yes, this library for clien and springboot as a server

**Comment by marci4** [comment] 2024-06-19 20:11
No example and no real str provided.
Closing as cannot reproduce

**Closed by marci4** 2024-06-19 20:11 UTC
Labels: missing-information, cannot-reproduce
