### ISSUE TITLE
Help!!! WebsocketClient onMessage not call when too long message

### ISSUE THREAD

**Issue by khacdai37** [TooTallNate/Java-WebSocket#378] opened 2016-04-21 07:17 UTC
I develop on the Android, I create a app chat group and I have a issue when my sever send too long message unread to my app and "onMessage" not called :(
wrong?
thanks.

**Comment by evan505** [comment] 2016-09-12 07:56
I'm having a similar issue in another library that uses Java-WebSocket. do you solve it

**Comment by marci4** [comment] 2017-03-20 16:26
duplicate of #423

**Closed by marci4** 2017-03-20 16:26 UTC
