### ISSUE TITLE
Server socket crash!

### ISSUE THREAD

**Issue by dragonlr** [TooTallNate/Java-WebSocket#338] opened 2015-09-12 00:43 UTC
Sometime server socket is die(crash) and i find in log this error, please help me fix it!

java.lang.NullPointerException
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:321)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:709)
2015-09-11 09:52:24,455 ERROR [MainSicbo] onError
java.lang.InterruptedException
    at java.lang.Object.wait(Native Method)
    at java.lang.Thread.join(Thread.java:1186)
    at java.lang.Thread.join(Thread.java:1239)
    at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:229)
    at org.java_websocket.server.WebSocketServer.stop(WebSocketServer.java:235)
    at org.java_websocket.server.WebSocketServer.handleFatal(WebSocketServer.java:464)
    at org.java_websocket.server.WebSocketServer.access$100(WebSocketServer.java:51)
    at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:716)

**Comment by marci4** [comment] 2017-03-30 18:21
hello @dragonlr,

does this issue still exists with the lastest lib version?

Greetings
marci4

**Comment by marci4** [comment] 2017-06-06 18:13
Cannot reproduce this issue...
And did not get any feedback

Closing it!

Greetings
marci4

**Closed by marci4** 2017-06-06 18:13 UTC
Labels: waiting-for-feedback
