### ISSUE TITLE
WSS Server: succeeded firstly then failed afterwards with chrome/IOS

### ISSUE THREAD

**Issue by jiangjianping** [TooTallNate/Java-WebSocket#958] opened 2019-12-16 12:43 UTC
We are running this wss server under android. There is no any problem to connect with this server using wss client under android. The wss client of chrome can also work with this server firstly. But if we close the wss connection and connect with this WSS server again, it failed mostly. We found that the chrome  omitted the "Client Key Exchange..." after the first established connection. The IOS websocket client had the same problem.

**Comment by PhilipRoman** [comment] 2019-12-16 12:50
Can you provide some code or application which reproduces this issue?

**Comment by jiangjianping** [comment] 2019-12-16 13:00
Hello,
I attached the packet captured by wireshark. In my opinion, The server may tell the client it can cache the session(key), but the time is very short. The connection created by chrome had "client key exchange..." firstly, then we close this connection and open the websocket connection  with wss server again, the "client key exchange..." missed.

![noclientkeyexchange](https://user-images.githubusercontent.com/14144270/70908594-8175c500-2046-11ea-9fb6-f408aaf16053.png)
![withclientkeyexchange](https://user-images.githubusercontent.com/14144270/70908595-820e5b80-2046-11ea-89b0-4ea2523fba7a.png)

**Comment by jiangjianping** [comment] 2019-12-17 00:45
the code we use is  just the SSLServerExample.java. The problem is due to session reuse.

**Comment by jiangjianping** [comment] 2019-12-17 10:29
We patched with the code from #943 , It seemed that the problem was solved. It is reasonable that the chrome not use Fast False firstly, but  session reuse will have the same effect as "Fast False" afterwards.

**Comment by majorasmask9** [comment] 2020-01-03 03:44
I appear to be experiencing the same issue as you. Implenting the bug fix you linked to has appeared to significantly reduce the number of failed connections, but I still do occasionally have issues whenever I restart the server. Totally ballparking here: I'd say before that bug fix, I'd experience issues 4/5 times, but afterward it's closer to 1/10 times. I can't really contribute any solutions or possible reasons as to what could be causing the issue, but figured I'd mention it at the very least.

**Comment by junaidnom** [comment] 2020-02-18 21:03
I'm having similar issues. Not sure what it is.
Is there a way to disable or reset the "session reuse" stuff?

**Comment by junaidnom** [comment] 2020-02-19 18:12
So for now taking a pause because updating the library at least got rid of the "sticky" behavior and now the failure rate is only about 1/30, and is not sticky (retrying connection works).

Next steps:
Check if its frontend/backend issue:
 - Make a very simple ws backend in JS or something and see if this occurs.

Replace java backend:
 - Try a different java socket library see if it occurs

**Comment by marci4** [comment] 2020-02-19 20:20
@junaidnom you should report this error to the developer of the other endpoint.
The response to a ping is required by the specification!

Best regards,
Marcel

**Comment by marci4** [comment] 2020-09-26 16:06
Closing issue as it was solved with #943

**Closed by marci4** 2020-09-26 16:06 UTC
Labels: missing-information
