### ISSUE TITLE
WebSocketClient use Assertion which leads to an un-catchable SocketTimeoutException  

### ISSUE THREAD

**Issue by avenwu** [TooTallNate/Java-WebSocket#361] opened 2015-12-23 02:58 UTC
Thank you for this great project;
After using the Java-WebSocket we found some SocketTimeoutException, so I dig into the source code, and find this below code inside WebSocketClient:

    // Runnable IMPLEMENTATION /////////////////////////////////////////////////
	public void run() {
		if( writethread == null )
			writethread = Thread.currentThread();
		interruptableRun();

		assert ( !channel.isOpen() );

	}

My question is about the  "assert ( !channel.isOpen() );" 
It seems not a good idea to assert in an thread which can hardly be monitor or catch by developer.

**Comment by bendem** [comment] 2015-12-23 11:34
This assertion specifies that an unclosed channel **when the thread finishes** is a bug. It has no impact on the thread logic and has nothing to do with a timeout. Moreover, assertions are disabled by default; you'd need to run your application with `-enableassertion` for it to have any effect (that is, throwing `AssertionError` if the condition was false).

So I doubt your problem comes from there. Maybe you could provide some reproduction steps if the problem is easily reproducible or at least the stacktrace and more information about the state of the application when the problem happens.

**Comment by avenwu** [comment] 2015-12-26 17:33
Thanks for your reply.
Personally I only use assertions in unit test, in fact I do not know much about assertions.
After google some resources, it seems that your point is right, assertion may have no impact default.

But I have got this error and it's definitely caused by assertion.
I use the project on android devices with no special configurations;

Here is my the exception stacktrace:
```
java.lang.AssertionError
java.net.SocketTimeoutException: failed to connect to comet.domain.com/119.254.211.135 (port 80) after 90000ms: isConnected failed: ETIMEDOUT (Connection timed out)
libcore.io.IoBridge.connect(IoBridge.java:102)
java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:177)
org.java_websocket.a.d.j(WebSocketClient.java:210)
org.java_websocket.a.d.run(WebSocketClient.java:188)
java.lang.Thread.run(Thread.java:841)
cause by:
java.net.SocketTimeoutException:failed to connect to comet.domain.com/119.254.211.135 (port 80) after 90000ms: isConnected failed: ETIMEDOUT (Connection timed out)
libcore.io.IoBridge.isConnected(IoBridge.java:247)
libcore.io.IoBridge.connectErrno(IoBridge.java:178)
libcore.io.IoBridge.connect(IoBridge.java:112)
libcore.io.IoBridge.connect(IoBridge.java:100)
java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:177)
org.java_websocket.a.d.j(WebSocketClient.java:210)
org.java_websocket.a.d.run(WebSocketClient.java:188)
java.lang.Thread.run(Thread.java:841)
cause by:
libcore.io.ErrnoException:isConnected failed: ETIMEDOUT (Connection timed out)
libcore.io.IoBridge.isConnected(IoBridge.java:234)
libcore.io.IoBridge.connectErrno(IoBridge.java:178)
libcore.io.IoBridge.connect(IoBridge.java:112)
libcore.io.IoBridge.connect(IoBridge.java:100)
java.nio.SocketChannelImpl.connect(SocketChannelImpl.java:177)
org.java_websocket.a.d.j(WebSocketClient.java:210)
org.java_websocket.a.d.run(WebSocketClient.java:188)
java.lang.Thread.run(Thread.java:841) 
```

**Comment by bendem** [comment] 2015-12-26 17:40
Kinda hard to do anything with an obfuscated stacktrace...

**Comment by avenwu** [comment] 2015-12-27 05:32
The obfuscation does not make it difficult to found out the WebSocketClient failure with source line number out there.

This project  seems no longer being maintained?
The last active contributions is years ago.
Anyway, thanks for your kindly replys

**Comment by bendem** [comment] 2015-12-27 09:42
You do realize [line 210 in WebSocketClient](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java#L210) is a `}` right?
So I'm guessing it is actually L166 which is in a try/catch so the exception thrown would be handled L172 and the return L174 would prevent it from ever reaching the assert L195.

And yes, the last contribution is half a year old. Maybe someone with commit access has a comment about that. /cc @ThreaT, @BrushfireDigitalServices

**Comment by ThreaT** [comment] 2015-12-27 13:57
@bendem Sorry, I've been busy with other stuff, what do you need done exactly?

**Comment by bendem** [comment] 2015-12-27 14:16
@ThreaT well, I don't really need anything specific, it's just true that the development is nowhere near active, the last milestone marked for months ago still contains 8 open issues (7 marked as bugs) and  there is a total of 36 issues open as bugs.

Since you are with @BrushfireDigitalServices the last 2 active committers for the project, I thought you would be the most appropriate people to make a statement about @avenwu's claim.

I'm not relying on this project anymore so I can't really tell, but if there is no intention to further update the project, it's ok but it could be made clear somewhere.

**Comment by ThreaT** [comment] 2015-12-27 14:21
@bendem We were verifying pull requests before committing them not too long ago but it takes a lot of time to double check and make sure they work. If someone's willing to do that and tell me which ones are safe, I'd be glad to merge them.

**Comment by vinod1054** [comment] 2015-12-29 07:52
same problem in my case also...getting crashes because of assertion statement in 1.3.0 veresion

**Comment by vinod1054** [comment] 2015-12-30 07:29
channel.connect( new InetSocketAddress( host, port ) );
			conn.channel = wrappedchannel = createProxyChannel( wsfactory.wrapChannel( channel, null, host, port ) );

			timeout = 0; // since connect is over
			sendHandshake();
			readthread = new Thread( new WebsocketWriteThread() );
			readthread.start();
		} catch ( ClosedByInterruptException e ) {
			onWebsocketError( null, e );

// Here we should close the connection to get rid of assertion error.
			return;
		} catch ( /*IOException | SecurityException | UnresolvedAddressException*/Exception e ) {//
			onWebsocketError( conn, e );
			conn.closeConnection( CloseFrame.NEVER_CONNECTED, e.getMessage() );
			return;
		}

**Comment by bendem** [comment] 2015-12-30 09:43
As I suspected, the assertion has nothing to do with a Java-Websocket assert statement. It looks like `channel.connect` calls [this method](http://grepcode.com/file/repo1.maven.org/maven2/org.robovm/robovm-rt/0.0.3/libcore/io/IoBridge.java#98) with or without a timeout, which means it's either directly forwarded to a [native method](http://grepcode.com/file/repo1.maven.org/maven2/org.robovm/robovm-rt/0.0.3/libcore/io/Posix.java#36) which thows a SocketTimeoutException, or handled on the java side by setting the socket to non blocking and [polling its status](http://grepcode.com/file/repo1.maven.org/maven2/org.robovm/robovm-rt/0.0.3/libcore/io/IoBridge.java#154) until it's connected or the timeout is hit. That exception is [handled on the calling site by wrapping it in an AssertionError](http://grepcode.com/file/repo1.maven.org/maven2/org.robovm/robovm-rt/0.0.3/libcore/io/IoBridge.java#102).

The best fix for this would then be imo to catch `AssertionError` when calling `connect` and calling the error code (`onWebsocketError` and `closeConnection` with `NEVER_CONNECTED`) if the exception cause is an `IOException`.

**Comment by vinod1054** [comment] 2015-12-30 10:41
Fatal Exception: java.lang.AssertionError
java.net.SocketTimeoutException: failed to connect to xyz.com after 90000ms: isConnected failed: ETIMEDOUT (Connection timed out)

How can i reproduce this error.

By the way how come Assertion description is having SocketTimeoutException( Error is showing Exception description)

**Comment by bendem** [comment] 2015-12-30 11:09
I just answered that question, see the message above...

> That exception is handled on the calling site by wrapping it in an AssertionError.

**Comment by vinod1054** [comment] 2015-12-30 11:24
thanks @bendem ..I got this now.
How can I reproduce this situation.
I tried with keeping 180 seconds timeout on my server, in this case it is just saying "Connection timeout".
But I am not getting "java.net.SocketTimeoutException: failed to connect to xyz.com after 90000ms: isConnected failed: ETIMEDOUT"

**Comment by bendem** [comment] 2015-12-30 12:02
I'm not sure I understand, the server doesn't connect to anything so changing its timeout will not do anything.
This issue is a client side problem. If your problem is server side, it belongs to another issue.

**Comment by vinod1054** [comment] 2015-12-30 12:06
ok....Thanks @bendem

**Closed** 2016-03-03 08:12 UTC
