### ISSUE TITLE
Error without exception in websocketserver

### ISSUE THREAD

**Issue by incapable** [TooTallNate/Java-WebSocket#296] opened 2014-12-11 09:35 UTC
After running for a few hours the server suddenly decided to call the onError method in the websocketserver. The call did not have a websocket attached and there was no exception either so it seems.

Problem here, there is no stack trace to be shown because simply, there isn't one.

After this error the complete websocketserver stopped running.

**Comment by marci4** [comment] 2017-04-26 09:45
I added some additional logging for some exceptions.

Cant reproduce it. And the pull request is just f**ed up.

Closing issue.
Greetings
marci4

**Closed by marci4** 2017-04-26 09:45 UTC
Labels: Bug, Server
