### ISSUE TITLE
Exception with sending ping without server access

### ISSUE THREAD

**Issue by tiagosantos1988** [TooTallNate/Java-WebSocket#579] opened 2017-10-20 10:38 UTC
There is a problem with sending ping. If there isn't server access it throws an exception. It didn't happend in version 1.3.4.

**Comment by tiagomartines11** [comment] 2017-10-20 16:10
I believe the new version is failing to detect some disconnection state before dispatching internal commands.
These are some traces that are related to this issue:
```
Fatal Exception: org.java_websocket.exceptions.WebsocketNotConnectedException
--
  | org.java_websocket.WebSocketImpl.send (WebSocketImpl.java:608)
  | org.java_websocket.WebSocketImpl.sendFrame (WebSocketImpl.java:634)
  | org.java_websocket.WebSocketImpl.sendPing (WebSocketImpl.java:641)
  | org.java_websocket.AbstractWebSocket$1.run (AbstractWebSocket.java:132)
```

```
Fatal Exception: org.java_websocket.exceptions.WebsocketNotConnectedException
--
  | org.java_websocket.WebSocketImpl.send (WebSocketImpl.java:608)
  | org.java_websocket.WebSocketImpl.sendFrame (WebSocketImpl.java:634)
  | org.java_websocket.WebSocketImpl.close (WebSocketImpl.java:440)
  | org.java_websocket.WebSocketImpl.close (WebSocketImpl.java:569)
  | org.java_websocket.client.WebSocketClient.close (WebSocketClient.java:190)
```

**Comment by marci4** [comment] 2017-10-21 07:16
Please use the template provided for any bug report...

**Comment by tiagosantos1988** [comment] 2017-10-23 15:28
The problem I'm having is exactly that quoted by @tiagomartines11 .

**Comment by marci4** [comment] 2017-10-24 19:25
With your poor description, it took me half an hour to reproduce your first issue with sendPing().

Without proper steps to repeat I cannot reproduce the second issue!

Greetings
marci4

**Comment by marci4** [comment] 2017-11-09 17:59
Should be fixed with new version..

Closing issue!
Greetings
marci4

**Closed by marci4** 2017-11-09 17:59 UTC
Labels: Bug, Client, missing-description
