### ISSUE TITLE
wss/ssl problem -  Continuous frame sequence was not started.

### ISSUE THREAD

**Issue by GalloTeo** [TooTallNate/Java-WebSocket#372] opened 2016-02-14 01:58 UTC
Hi guys, i have a problem using the web socket server when i turn on the ssl 
i can connect properly to the server but after few packets sent to the websocket server i get 

```
on Socket Error java.nio.BufferOverflowException
on Socket Error org.java_websocket.exceptions.InvalidDataException: Continuous frame sequence was not started.
```

sometime instead i receive 
`on Socket Error org.java_websocket.exceptions.InvalidFrameException: bad rsv 4`

or
`on Socket Error org.java_websocket.exceptions.InvalidFrameException: bad rsv 1`

the error seems to be more evident or easy to be reproduced with large packets, but even chunking the packets in smaller ones, it is present. 

the problem is not dependent on the code itself, it's easy to be reproduced with just a dummy client which sends bytes.

i created the SSLContext like this 
[https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLServerExample.java](url)

i created the jks file from the .crt one because i could not find a way to directly load that and apply the RSA key. In addition i so that in your example there was the usage of jks so i guessed it as common practice. 

any clue ? 

thank you

**Comment by marci4** [comment] 2017-03-30 18:13
Hello @GalloTeo,

do you still have this issue with the most recent lib version?

Which draft are you using?

Personally I dont have any issues with wss in my IDE and in production.

Greetings
marci4

**Comment by marci4** [comment] 2017-05-05 12:11
Cannot reproduce.
No feedback.

Probably fixed with some commits.
Closing.
Greetings
marci4

**Closed by marci4** 2017-05-05 12:11 UTC
Labels: waiting-for-feedback
