### ISSUE TITLE
Unable to build using 'ant'

### ISSUE THREAD

**Issue by prithivraj** [TooTallNate/Java-WebSocket#456] opened 2017-04-19 08:13 UTC
Socket-master/build/classes
    [javac] javac: target release 1.6 conflicts with default source release 1.8
BUILD FAILED
/Users/prithivraj-1942/Desktop/Java-WebSocket-master/build.xml:9: Compile failed; see the compiler error output for details.

**Comment by marci4** [comment] 2017-04-19 08:33
Hello @prithivraj,

right now I cannot reproduce your issue.

I DO get a warning for the wrong source version which I am gonna fix, but other then that, my build succeeds.

Greetings
marci4

**Comment by marci4** [comment] 2017-04-24 09:34
Fixed some warnings.

Closing issue.
Greetings
marci4

**Closed by marci4** 2017-04-24 09:34 UTC
Labels: waiting-for-feedback, works-for-me
