### ISSUE TITLE
When using self-signed, multiple connections crashes server

### ISSUE THREAD

**Issue by hydrabolt** [TooTallNate/Java-WebSocket#326] opened 2015-07-26 13:40 UTC
So I'm hosting a Web Socket Server with a self-signed SSL license. It works until there is more than 1 connection. The third connection kills the server and it stops responding. The server runs on android and I'm connecting to it using WebSockets. Here's a stacktrace:

http://hastebin.com/uxoxalarab.avrasm

any ideas? thanks

**Comment by BrushfireDigitalServices** [comment] 2015-07-27 20:02
The server should not crash/become unresponsive due to failed connections, but here it does. All three attempts in the stack trace are failing.

Are you sure that your client is configured to accept the current version of your self-signed certificate? The stack trace looks like that's the underlying issue to me.

I've tagged this as unclear until we can determine whether this is tied to an untrusted cert issue. If so, there's still likely diagnostics to be done.

**Comment by hydrabolt** [comment] 2015-07-27 20:04
It should do, I went to https://192.168.0.8:25517/ (where my WSS server runs), accepted the certificate and opened websockets to it in chrome.

**Comment by BrushfireDigitalServices** [comment] 2015-07-27 20:16
Ok. Adjusted tags accordingly. What is the source of the NPE on line 161 of the stack trace?

**Comment by hydrabolt** [comment] 2015-07-27 20:19
I've no idea, although I updated the version of this library I'm using and now it doesn't error but it still crashes :\

**Comment by BrushfireDigitalServices** [comment] 2015-07-27 20:37
We can still try to help sort it out. We recently changed WebSocketServer and SSLSocketChannel2, so it might be related to #307 or #171. Do you happen to know which commit of this library you were previously using?

Are you experiencing CPU or memory leak symptoms before or during the crash?

**Comment by hydrabolt** [comment] 2015-07-27 21:20
I'm not sure, although it was fairly old. I think 1.3.0?

I will check for CPU and memory leaks tomorrow ;) 

Thanks for your help!

**Comment by hydrabolt** [comment] 2015-07-28 19:51
I don't believe there were any CPU or memory leaks, however I think there must be something wrong during the handshake as the onOpen event is not even called.

**Comment by hydrabolt** [comment] 2015-07-28 20:53
I have found a development in this issue, and am very sure that is an isolated case within Chrome (not tested on other browsers). I just did a spam connect using Java and it was fine, there were no errors. This leads me to believe that you were correct @BrushfireDigitalServices, it seems that chrome is messing up something with SSL.

**Comment by BrushfireDigitalServices** [comment] 2015-07-29 04:10
@hydrabolt I'm glad that reconnecting the client helps in the short term. Perhaps Chrome is not meeting the protocol specs, perhaps they are within them and this library needs to account for it. Either way we definitely need to find a reusable way to stop client behavior from DoS-ing the server!

Resource leaks were an unlikely guess in the first place, but since the fixes are so recently introduced, I felt it best to ask. 

- Do you feel confident investigating the details of the handshake?

- Issue #300 is also specific to Chrome, though your problem looks to be in the handshake with message lengths that shouldn't trigger it. If you have the opportunity to test your project with another browser, the results would be valuable to us. Please upload logs when available.

- Issue #210 looks similar, but the reported fix is now included. We should check if the suggested malicious command will still reproduce this issue.

- Pull request #297 isn't merged yet, but *may* work correctly for you.

**Comment by hydrabolt** [comment] 2015-07-29 17:04
I'm not that confident with the handshake, and I'll post more details later

**Comment by BrushfireDigitalServices** [comment] 2015-07-29 17:47
Looking into the handshakes should probably wait until after the other tests anyway. The key point is being able to get a set of packet captures and program logs, preferably one of a failed connection and one successful. From there, I can look into what's going wrong.

Thanks for your patience throughout this process.

**Comment by hydrabolt** [comment] 2015-07-29 20:13
Hi again @BrushfireDigitalServices 

The most I've been able to salvage from the errors were the stacktraces above

**Comment by BrushfireDigitalServices** [comment] 2015-07-30 23:56
Understood. I'll try to reproduce the issue in the emulator and update with my findings in a few days.

**Comment by hydrabolt** [comment] 2015-08-01 21:05
Thank you @BrushfireDigitalServices. I've been unable to access my computer for a few days and won't be able to for a week or so, so I've been unable to provide more information.

**Comment by BrushfireDigitalServices** [comment] 2015-08-02 04:58
You're welcome, @hydrabolt. Hopefully by the time you have access to your computer we'll have something actionable. 

Although I have experience with desktop Java and troubleshooting, I may need to follow up with a few Android-newbie questions as I work on the test app. Which SDK version or versions are you running your server on?

**Comment by hydrabolt** [comment] 2015-08-02 07:37
It requires a minimum of android 4.2 and should be built with the latest SDK @BrushfireDigitalServices

**Comment by hydrabolt** [comment] 2015-08-02 07:39
I can't seem to edit from my mobile but all the SDK references in my project are [here](https://github.com/TitanCast/TitanCast/blob/master/app/build.gradle)

**Comment by BrushfireDigitalServices** [comment] 2015-08-04 00:37
Progress update:

No luck emulating a wifi connection. I have one physical device that I may be able to load with new enough android to test. 

I have some *completely untested* theories about why the server is becoming unresponsive. If correct, it would mean the unresponsive issue is in Titancast and the bad handshake issue is somewhere between Java-Websocket and Chrome.

Am still working on setting up a toolchain to sniff the handshake packets and test my theories.

**Comment by hydrabolt** [comment] 2015-08-04 11:36
OK! Thanks for your help with this issue!

**Comment by marci4** [comment] 2017-04-03 07:07
Hello @hydrabolt ,

is this still an issue for you with the latest version of the lib?

Greetings
marci4

**Comment by marci4** [comment] 2017-05-28 20:05
Updated some code with #488.

Does this fix it for you?
Greetings
marci4

**Comment by hydrabolt** [comment] 2017-05-28 21:31
Hi! I've since given up on the project I was working on so I'm no longer able to check, sorry

**Comment by marci4** [comment] 2017-05-28 21:52
No problem. Thanks for your feedback

I'm gonna close this issue since I am not able to reproduce it locally!
Greetings
marci4

**Closed by marci4** 2017-05-28 21:52 UTC
Labels: Android, Bug, Server, waiting-for-feedback, wss
