### ISSUE TITLE
Crash caused by sendPing in restartConnectionLostTimer

### ISSUE THREAD

**Issue by yperess** [TooTallNate/Java-WebSocket#721] opened 2018-06-15 15:33 UTC
## Expected Behavior
`sendPing` should only be called when the connection is valid.

## Current Behavior
`sendPing` is called but throws `WebsocketNotConnectedException`

## Possible Solution
Wrap the call here https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/AbstractWebSocket.java#L173 with a try/catch

## Steps to Reproduce (for bugs)
I'm sorry, it's super hard to reproduce this. Our app that's using this library has ~1k dau and I've seen this crash twice in a month.

## Debug log (for bugs)
Here's a copy of the crash report from Crashlytics:
```
org.java_websocket.WebSocketImpl.send (WebSocketImpl.java:608)
org.java_websocket.WebSocketImpl.sendFrame (WebSocketImpl.java:634)
org.java_websocket.WebSocketImpl.sendPing (WebSocketImpl.java:641)
org.java_websocket.AbstractWebSocket$1.run (AbstractWebSocket.java:153)
java.util.TimerThread.mainLoop (Timer.java:555)
java.util.TimerThread.run (Timer.java:505)
```

## Context
Building a live gameshow app.

## Your Environment
* Version used: 1.3.8
* Java version: 1.8
* Operating System and version: Android
* Endpoint Name and version: npm's ws:5.1.1
* Link to your project: https://play.google.com/store/apps/details?id=io.gometa.yas

**Comment by marci4** [comment] 2018-06-17 17:09
Duplicate of #715

**Closed** 2018-06-17 17:10 UTC
