### ISSUE TITLE
In Android, if the WebSocket sends Message too large, the Message received in the OnMessage is incomplete.

### ISSUE THREAD

**Issue by AnandLin** [TooTallNate/Java-WebSocket#641] opened 2017-12-28 04:43 UTC
Hi,I met a problem in Android.
In Android, if the WebSocket sends Message too large, the Message received in the OnMessage is incomplete.Does java-websocket need to set the message size?

**Comment by marci4** [comment] 2017-12-28 13:34
Hello @AnandLin,

thank you for your issue!
No, this lib does not have a specific message size apart from the Integer.MaxValue limit due to using bytebuffer.

Could you please fill out this template and provide some steps to repeat for me so I can reproduce and fix this issue!
Thank you.

Greetings
marci4


```
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- If you're describing a bug, tell us what should happen -->
<!--- If you're suggesting a change/improvement, tell us how it should work -->

## Current Behavior
<!--- If describing a bug, tell us what happens instead of the expected behavior -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Debug log (for bugs)
<!--- Please provide a debug log for your issue. -->
<!--- You can activate the debug log with 'WebSocketImpl.DEBUG = true;' -->

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
* Java version:
* Operating System and version:
* Endpoint Name and version:
* Link to your project:
```

**Comment by AnandLin** [comment] 2017-12-29 02:05
Think you for your answer,But I tried to use Java-websocket 1.3.1 and 1.3.7 versions, and I found that the message received is incomplete!

My data is provided by javaWeb server. I try to get data from java-WebSocket's WebSocketImpl#socketBuffer, get the result data can be received, but subcontracted. I look at the data package processing in java-WebSocket, but it seems to be that the data is incomplete after Draft_6455#translateSingleFrame processing. I don't understand the bottom of the WebSocket very well, and the format of the data I receive is as follows:
{
"Method": "OL_AGENT_RequestUnReadMsgAck",
"RetCode": "XXXX",
"RetMsg": "XXXX",
"OriginId": "XXXX",
"OpenId": "XXXX",
"SessionId": "conversation ID",
"Data": "recId" [{: "ID", "sessionType" records: "the session type", "msgType", "information", "content" type: "content", "createTime": "the creation time"}]
}
When data data is too much, the whole JSON is incomplete!

**Comment by marci4** [comment] 2017-12-29 09:30
Hello @AnandLin,

I would still like to know on which Android version this happens.

Also why are you using WebSocketImpl#socketBuffer for receiving any data and not the normal WebSocketClient#onMessage method?
Could you also provide a link to the javaWeb project, I did not find anything in my search!

Apart from this could you maybe send me your project so I can take a detailed look?

Greetings
marci4

**Comment by marci4** [comment] 2018-01-08 07:39
Hello @AnandLin,

could you provide an update for this issue?

Greetings
marci4

**Comment by AnandLin** [comment] 2018-01-09 02:40
Hello @marci4,
      I am so sorry!It's quite busy in the previous period.
      I can't provide the corresponding java-web service.When I try my text data enough, the data is incomplete and the size of the data is estimated to be around 5M. My Android version 4.4 and 5.0 will be in this situation!Do I see you and processing time, source logic is compared with a buffer size to see whether the push end of the message.look draft_6455 # translatesingleframe.I'm not very familiar with the principle of websocket dismantling.

**Comment by marci4** [comment] 2018-01-09 05:55
Hello @AnandLin,

Right now I am not sure if I can help you with no information. 

You do not use the provided template to provide me with debug information or steps to repeat.
You cannot provide any information for the other endpoint.
I have no idea what you are doing so I cannot help you...

Greetings 
marci4

**Comment by marci4** [comment] 2018-01-28 16:31
Any update?

**Comment by marci4** [comment] 2018-03-05 17:10
Dead issue!

Closing it!
If there is new feedback, feel free to reopen it!

Greetings
marci4

**Closed by marci4** 2018-03-05 17:10 UTC
Labels: Android, Unclear, missing-template
