### ISSUE TITLE
Connection disconnected when communicating with other Websocket library servers. 

### ISSUE THREAD

**Issue by santoshJD** [TooTallNate/Java-WebSocket#993] opened 2020-03-24 05:54 UTC
Scenario:
i am using websocket client :: tootallnate ,
                 websocket server :: uWebSockkets https://github.com/uNetworking/uWebSockets

problem is  when ping pong is enabled on uWebSocket server , after sending one message from webSocket client , 2nd time it gets disconnected 

"code=1006 and no reason" 

can think of any solution .  will appreciate any help.

**Comment by marci4** [comment] 2020-03-24 07:14
Hello @santoshJD,
could you please provide a example implementation for the websocket server?

Thx a lot.

Best regards,
Marcel

**Comment by santoshJD** [comment] 2020-03-24 11:06
https://github.com/uNetworking/uWebSockets/blob/master/examples/EchoServer.cpp

**Comment by marci4** [comment] 2020-03-24 22:49
This issue can be reproduced with chrome and firefox.
Therefore it is most likely a server error and not caused by this project.

Closing issue.
Best regards,
Marcel

**Closed by marci4** 2020-03-24 22:49 UTC
Labels: Client, cannot-reproduce
