### ISSUE TITLE
OnClose is not called when client disconnect

### ISSUE THREAD

**Issue by kunluo2019** [TooTallNate/Java-WebSocket#900] opened 2019-06-05 19:28 UTC
We just upgraded to the latest version. And I noticed that if client process is killed, On server side, onClose is not called. Instead after 30 seconds or so (related to default value in setConnectionLostTimeout), onClose is then called.

Because we were using a old version before, we know, in old version, if we kill the client process, server side, onClose is immediately get called.

Now, it does not do that.

I searched your bug report and found that bug #886 also described the similar situation.

Is this intented change? or there is way for server side to immediately know client socket disconnection?

**Comment by marci4** [comment] 2019-06-11 17:42
Hello @kunluo2019,

no there were no (intentional) changes to that behaviour. 

What two versions are you comparing?
Could you provide an example code?

Best regards,
Marcel

**Comment by kunluo2019** [comment] 2019-06-11 22:27
The issue can be reproduced by compiling sample ChatServer and ChatClient program with old/new websocket library.

After ChatClient is connected to ChatServer

In old version, if I kill ChatClient, ChatServer will immediately printout "has left the room!" message.

In new version, ChatServer won't print that message until the timeOut has reached (setConnectionLostTimeout(100) for 100 seconds in ChatServer code).

If you can tell me how to print the version info from the websocket.jar file, I can provide you corresponding old version number.

The new version is latest 1.4.0.

thanks

**Comment by marci4** [comment] 2019-06-12 07:11
What is your old version?

**Comment by kunluo2019** [comment] 2019-06-12 12:00
I downloaded around Jan 2018, so it should be between 1.3.7 and 1.3.8.

I still have the corresponding source code.

Does the source code have embedded version number? If so, I can find out.

**Comment by marci4** [comment] 2019-06-12 12:06
Pom.xml should contain the version. 

Best regards,
Marcel

**Comment by kunluo2019** [comment] 2019-06-12 12:15
1.3.8

thanks

**Comment by marci4** [comment] 2019-06-12 19:56
No I was not able to find any change that jump out. 

Could you please provide a unit test which shows the issue?

Thank you!

Best regards,
Marcel

**Comment by kunluo2019** [comment] 2019-06-12 21:12
If you just compile the sample ChatServer and ChatClient that are in examples directory as part of Java-WebSocket, run it, you will see the issue.

In the latest version, if you kill ChatClient, ChatServer will not print "has left the room!" until 100 second timeout has reached.

If you need me to provide the old version, I can upload it for you.

thanks

**Comment by maiph** [comment] 2019-06-12 21:43
I was able to reproduce it.

1. Start the CharServer
2. Start 2 ChatClient
3. Press connect on both clients
4. Kill one of the ChatClient
5. The message "has left the room" takes a while to show

I didn't test an older version, only the current version on master `1.4.1-SNAPSHOT`

**Comment by marci4** [comment] 2019-06-24 20:55
Was able to reproduce the issue!

Fixed it and steps to repeat work and currently working on a unit test.

Best regards,
Marcel

**Comment by marci4** [comment] 2019-06-28 16:08
To be honest I am not sure if I can even write a test for this issue.

Normally closing the socket of the WebSocketClient does not trigger the IOException since it is a normal close.
I would have to start a separate process for the client and kill this process, so the JVM then triggers the IOException on the server side.

Anyone else has an idea?

Best regards,
Marcel

**Comment by maiph** [comment] 2019-06-28 16:12
Can you share the fix for this issue? Maybe that can give some insight on how to reproduce other can spawning a new process.

**Comment by marci4** [comment] 2019-06-28 16:18
Pushed the changes to branch Issue900 (https://github.com/marci4/Java-WebSocket-Dev/tree/Issue900)

**Comment by maiph** [comment] 2019-06-28 16:29
Can't we force the underlying socket to close using reflection ?

**Comment by marci4** [comment] 2019-06-28 16:52
I tried it this way https://gist.github.com/marci4/6b47a9475d440a3dcd0d5212095d5ab3 and it just triggers a close due to eot() being called.

**Comment by Lloyd0577** [comment] 2019-10-25 10:32
@marci4 use this 1.4.1.jar file ,build error :
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: org.java_websocket.SSLSocketChannel

**Closed** 2020-01-20 19:40 UTC
Labels: Bug, Server
