### ISSUE TITLE
On closing a connection, Websocket is stuck in READYSTATE.CLOSING

### ISSUE THREAD

**Issue by kimtuitoek** [TooTallNate/Java-WebSocket#677] opened 2018-03-05 21:31 UTC
When trying to check for whether `READYSTATE.CLOSED` is set by running `WebSocketImpl.isClosed()`. `READYSTATE` is always set to `CLOSING` after initiating a close/closeConnection.

## Expected Behavior

 `READYSTATE` should be set to `CLOSED` regardless of whether the close was normal or abnormal.

## Current Behavior

Whenever I query `WebSocketImpl.isClosed()`, I get false since `READYSTATE` is set to `CLOSING` regardless of whether the connection close was normal or abnormal.

## Possible Solution

Check the `WebSocketImpl.close(int, String, boolean)` method and verify that the method does not return without transition `READYSTATE` from `CLOSING` to `CLOSED`.

## Steps to Reproduce (for bugs)

1. Create a Websocket client( and Websocket server if not already)
2. Ensure that the connection is established between the server and the client.
3. Stop Websocket server.
4. Confirm whether `READYSTATE` is set to `CLOSED` after the connection is lost or wait until it is set.
5. Also check whether `READYSTATE` is  transitioned from `CLOSING` to `CLOSED`

## Context

I'm trying to re-establish a connection after a connection is lost.

## Your Environment

* Version used: 1.3.7
* Java version: JDK 1.8.0
* Operating System and version: Ubuntu 16.4
* Endpoint Name and version:
* Link to your project: Closed source

**Comment by marci4** [comment] 2018-03-06 18:18
Hello @kimtuitoek,

thank you for your issue report!

Even though I am pretty sure that this was also the same on 1.3.7, could you maybe update to 1.3.8?
Because I cannot reproduce your issue on the current master branch (so 1.3.8).

Let me clear some things up for you:
* This behaviour is the expected behaviour 
** Calling close() on a WebSocketClient will initiate the closing handshake. `The closing handshake is intended to complement the TCP closing handshake (FIN/ACK).`
** Initiating a closing handshake means that the WebSocketClient is sending a CloseFrame to the server and waiting for the server to respond with a CloseFrame.
** While the client is waiting for this frame, the connection is in the state: Closing (no new frames allowed, but the other endpoint may send still some data)
** After receiving the CloseFrame, the state will be changed to Closed
* closeConnection() does not care about this closing handshake and will directly close the socket and set the state to Closed

Hoe this clears some things up!

Greetings
marci4

**Comment by kimtuitoek** [comment] 2018-03-07 00:16
Thanks. I haven't tried out the new methods but those re-connection methods should solve my problem of trying for reconnection. That was what I was trying to do.

From the way you explained it, let's say the closing handshake is initiated by the WebSocketClient and the client is waiting for the server to respond with a CloseFrame, if the server goes down unexpectedly in the middle of the handshake, will the WebSocketClient detect this and transition to the closed state?

**Comment by marci4** [comment] 2018-03-07 17:20
Hello @kimtuitoek,

yeah that has do be detected by the underlying socket system. We also have a heartbeat feature for this on a lib level.
Both ways trigger the transition from closing to close in this case!

Greetings
marci4

**Comment by marci4** [comment] 2018-03-18 17:22
Any update?

**Closed** 2018-03-23 20:08 UTC
Labels: Info, cannot-reproduce
