### ISSUE TITLE
Address already in use when app crashed and restart

### ISSUE THREAD

**Issue by yokey1219** [TooTallNate/Java-WebSocket#758] opened 2018-08-16 09:39 UTC
When app crashed,and then restart ,get a "Address already in use" exception.
I checked with command 'netstat',there was some data in inqueue of local socket,so local socket cannot close.All the closed connection was in status 'CLOSE_TIMEWAIT'.
## Expected Behavior

Local socket can close.
## Current Behavior

Local socket can not  close.
## Possible Solution

Please give me some suggestion.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.3.9
* Java version:   7
* Operating System and version:Android 4.0+
* Endpoint Name and version:
* Link to your project:

**Comment by PhilipRoman** [comment] 2018-08-16 10:40
Have you tried using the setTcpNodelay(true) option? This should not be an issue caused by this library. Also, if possible you could allow the OS to pick a random free port instead of hardcoding it.

**Comment by yokey1219** [comment] 2018-08-17 01:27
I was trying the setReuseAddr(true) option,but it's still happened sometimes.Maybe it's caused by some unkown issue, so i need help.

**Comment by PhilipRoman** [comment] 2018-08-17 06:28
Does this only happen when your app crashes? Does it happen when the app is closed normally? I've also experienced this on one of my linux servers. In any case, the TIME_WAIT state should go away after a few minutes. The "reuseAddr" of this library simply forwards to the underlying Java socket APIs and there is nothing we can fix there. I will try to help the best I can though!

**Comment by yokey1219** [comment] 2018-08-17 09:59
Thanks for your reply. Yes, it only happens when the app crashes. I will try to reproduce this issue and provide more info.

**Comment by nsjames** [comment] 2018-08-28 10:54
I see this also happening ( consistently ) with `setReuseAddr(true)` when starting a server as the app starts, and then reloading the app in an emulator.

**Comment by marci4** [comment] 2018-08-28 18:03
Hello @nsjames,

could you maybe provide an example application (repository) and some steps to repeat?

Thank you!

Best regards,
marci4

**Comment by nsjames** [comment] 2018-08-28 20:42
The code is currently closed source but it'll be open source fairly soon.

I'll be sure to link the repo once it is!

**Comment by 8databit** [comment] 2018-09-16 22:15
The JVM is probably still running, well atleast i think the thread that initialized the socket did.
I never experienced the problem when properly closing the application that took a hold of the given ip/port.
Maybe you're using threads the wrong way.

**Comment by marci4** [comment] 2018-09-21 16:45
Last call for an example application, otherwise I will close this issue as cannot reproduce!

**Comment by nsjames** [comment] 2018-09-25 23:44
Not going to be able to open-source in time. I'll leave the link here once it is so that we can take it from there

**Comment by marci4** [comment] 2018-10-21 17:49
No source code provided..
Closing this as cannot reproduce!

Best regards,
marci4

**Closed by marci4** 2018-10-21 17:49 UTC
Labels: Android, Unclear
