### ISSUE TITLE
Option to ignore HTTP status code/line

### ISSUE THREAD

**Issue by cr5315** [TooTallNate/Java-WebSocket#647] opened 2018-01-13 10:04 UTC
## Current Behavior
The server I'm attempting to connect to (IRC) doesn't send an HTTP status code when the client connects, causing the library to immediately close the connection.

## Possible Solution
An option to have the Draft class not check for the initial HTTP status code when opening a connection.

## Context
The IRC server starts the connection by sending a line with the format `:server.network.net NOTICE * :*** Looking up your hostname...`, and never sends a HTTP status code or message.

## Your Environment

* Version used: 1.3.7
* Java version: Java 7, Kotlin 1.2.10
* Operating System and version: Android 8.1
* Endpoint Name and version: irc.freenode.net

**Comment by marci4** [comment] 2018-01-13 10:26
Hello @cr5315,

thank you very much for this issue and your interest in this project.

For me the problem is that the WebSocket-Protocol and IRC-Protocol are different in a lot of aspects.
The way how messages/frames are send is different as well as how a handshake is performed.

If you wanna connect to a IRC server with a WebSocket, you have to use a separate library like https://github.com/novnc/websockify.

I hope this clears some things up.

Greetings
marci4

**Comment by cr5315** [comment] 2018-01-13 10:35
Oh goodness, I wasn't aware that there was a difference between Socket and WebSocket 🤦‍♂️ ! Now I feel like a fool.

**Comment by marci4** [comment] 2018-01-13 10:37
Hello @cr5315,

that is not a problem at all ;) Happens the best of us.

There are still a lot of Java IRC libs out there. :) Just do a quick search on google.

Greetings
marci4

**Comment by marci4** [comment] 2018-01-28 16:31
Problem solved.

Closing issue!
Greetings
marci4

**Closed by marci4** 2018-01-28 16:31 UTC
Labels: Info
