### ISSUE TITLE
 NPE in SocketChannelIOHelper.read

### ISSUE THREAD

**Issue by scottslewis** [TooTallNate/Java-WebSocket#403] opened 2016-10-01 23:45 UTC
Hi.   We are using java websockets and on the server side while using ssl we are first getting and onError call with socket=null...i.e. tis WARN from our code

2016-10-01 13:26:58,715 | WARN  | socketSelector64 | http                             | 72 -  | WebSocketListener.onError socket=null

This is immediately followed by a stack trace from inside java websockets

java.io.IOException: An existing connection was forcibly closed by the remote host
    at sun.nio.ch.SocketDispatcher.read0(Native Method)[:1.8.0_101]
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)[:1.8.0_101]
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)[:1.8.0_101]
    at sun.nio.ch.IOUtil.read(IOUtil.java:197)[:1.8.0_101]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)[:1.8.0_101]
    at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:116)[71:java_websocket:1.3.1.201512181726]
    at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:75)[71:java_websocket:1.3.1.201512181726]
    at org.java_websocket.server.DefaultSSLWebSocketServerFactory.wrapChannel(DefaultSSLWebSocketServerFactory.java:39)[71:java_websocket:1.3.1.201512181726]
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:317)[71:java_websocket:1.3.1.201512181726]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]

This is followed by another onError socket=null call in our code...i.e.

2016-10-01 13:26:58,715 | WARN  | socketSelector64 | http                             || WebSocketListener.onError socket=null

and then this NPE in java websockets occurs

java.lang.NullPointerException
    at org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:12)[71:java_websocket:1.3.1.201512181726]
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:327)[71:java_websocket:1.3.1.201512181726]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]

Which seems particularly bad because it might affect the proper running of the WebSocketServer.run thread.

Sometimes the first stack trace appears above, and it's not followed by the second.

This is using a version/copy of java websockets built on Dec 18, 2015.

Any insights or suggests for collecting of other information to figure out what's going wrong here?

Thanksinadvance.  Scott

**Comment by marci4** [comment] 2017-03-17 12:38
Hello @scottslewis,

sorry for the delay. I am trying to get through all the old issues!!

Does the NPE still exists when you build your jar from the current master?

Greetings
marci4

**Comment by marci4** [comment] 2017-05-28 20:04
2 months of no feedback.

Cant reproduce this issue!
Closing it.
Greetings
marci4

**Closed** 2017-11-24 16:34 UTC
Labels: Unclear, waiting-for-feedback, works-for-me
