### ISSUE TITLE
maven build

### ISSUE THREAD

**Issue by mlybarger** [TooTallNate/Java-WebSocket#709] opened 2018-05-23 17:19 UTC
to build a jar, i needed to add this section to the maven pom:

```
         <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>1.7</version>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                      <source>src/main/example</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>

```

**Comment by marci4** [comment] 2018-05-24 17:08
Hello @mlybarger,

that is interesting since I am using this maven pom.xml to build the lib for the repository.

And I do not understand why the examples should be required for the build...
Could you explain this for me please?

Best regards,
marci4

**Comment by mlybarger** [comment] 2018-05-24 19:33
You're right. There's no need for that on the pom.  I do however get
sporadic errors from the unit tests which caused a problem for me
building.  I added that, and it built, but it is indeed not needed.  I
don't know why I get this random error.  It's very hard to recreate.  I did
get errors on both windows (java 7) and linux (java 8).


Running org.java_websocket.framing.BinaryFrameTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec
Running org.java_websocket.framing.CloseFrameTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running org.java_websocket.framing.ContinuousFrameTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.java_websocket.framing.FramedataImpl1Test
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Running org.java_websocket.framing.PingFrameTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.java_websocket.framing.PongFrameTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.java_websocket.framing.TextFrameTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.java_websocket.issues.Issue256Test
Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.421 sec
<<< FAILURE!
runReconnectScenario4(org.java_websocket.issues.Issue256Test)  Time
elapsed: 0.019 sec  <<< ERROR!
java.lang.NullPointerException
        at
org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:270)
        at
org.java_websocket.client.WebSocketClient.connectBlocking(WebSocketClient.java:279)
        at
org.java_websocket.client.WebSocketClient.reconnectBlocking(WebSocketClient.java:233)
        at
org.java_websocket.issues.Issue256Test.runTestScenarioReconnect(Issue256Test.java:119)
        at
org.java_websocket.issues.Issue256Test.runReconnectScenario4(Issue256Test.java:200)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at
org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)

Running org.java_websocket.issues.Issue580Test
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.51 sec
Running org.java_websocket.issues.Issue609Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec
Running org.java_websocket.issues.Issue621Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec
Running org.java_websocket.issues.Issue661Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.138 sec
Running org.java_websocket.issues.Issue666Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec
Running org.java_websocket.issues.Issue677Test
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec
Running org.java_websocket.misc.OpeningHandshakeRejectionTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec
Running org.java_websocket.protocols.ProtoclHandshakeRejectionTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.103 sec
Running org.java_websocket.protocols.ProtocolTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.java_websocket.util.ByteBufferUtilsTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

**Comment by marci4** [comment] 2018-05-24 19:51
Hello @mlybarger,

yeah I know about that sporadic issue. It is more an issue with the test itself then with the reconnect functionality.
The problem is that the WebSocketServer sometimes cannot handle more then 5 connections if the connect at the exact same moment (what happens with this test setup). Then the connection won't get established and everything breaks.

I "ignored" this sporadic error since I always planned to improve the behaviour of the WebSocketServer Selector anyway to reduce the blocking time on it!

Hope this clears some things up.

Best regards,
marci4

**Comment by marci4** [comment] 2018-06-29 16:49
Issue should be solved.

Closing it!

Best regards,
marci4

**Closed by marci4** 2018-06-29 16:49 UTC
Labels: Info, Unclear
