### ISSUE TITLE
Client does not transmit response

### ISSUE THREAD

**Issue by AlexRomanch** [TooTallNate/Java-WebSocket#330] opened 2015-08-07 08:03 UTC
Hi all.
In my project i use TooTallNate Websocket client in Java applet, which connected to serverEndpoint (use standard Java EE implementation javax.websocket). Each session consist of 300-400 text messages.
Got one trouble - sometimes server does not receive message from client, and server forced to repeat request. Why it may happen? Client logged information, that message succesfully sent, whithout any exceptions.
#### Client code:

``` java
 public void init() {
        super.init();
        try {
         client = (WebSocketClient) AccessController.doPrivileged(new PrivilegedExceptionAction<Object>() {
                public Object run() {
                    try {
                        return new WebSocketClient(new URI(remoteHost), new Draft_17()) {

                            @Override
                            public void onOpen(ServerHandshake handshakedata) {
                                System.out.println("new connection opened");
                            }

                            @Override
                            public void onClose(int code, String reason, boolean remote) {
                                System.out.println("closed with exit code " + code + " additional info: " + reason);
                                client.close();
                            }

                            @Override
                            public void onMessage(String message) {
                                System.out.println("<< Client got message: " + message);
                                String response = someLogic();
                                sendMessageToServer(response);
                            }

                            @Override
                            public void onError(Exception ex) {
                                System.out.println("exception!");
                            }
                        };
                    } catch (Exception e) {
                        e.printStackTrace();
                        return null;
                    }
                }
            });
            AccessController.doPrivileged(new PrivilegedExceptionAction<Object>() {
                public Object run() {
                    try {
                        client.connect();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    return null;
                }
            });
private void sendMessageToServer(String msg) {
        try{
            client.send(msg);
            System.out.println(">> Send message to server: " + msg);
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }

```
#### ServerEndpoint code:

``` java
 public class WebSocketServer {
    private Session session;

    public WebSocketServer() {
    }

    @OnOpen
    public void onOpen(Session session) {
        System.out.println(session.getId() + " has opened a connection");
        this.session = session;
    }
    @OnMessage
    public void onMessage(String message) {
        System.out.println("<< Server got message: " + message);

            Thread thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    String response = someLogic(message);
                    session.getBasicRemote().sendText(response);
                }
            });
            thread.start();
    }
    @OnClose
    public void onClose(Session session) {
        System.out.println("Session " + session.getId() + " has ended");
    }
    @OnError
    public void OnError(Throwable ex) {
        ex.printStackTrace();
    }
```

Any ideas? Thanks a lot.

**Comment by douglasjunior** [comment] 2015-10-20 16:25
Try change to:
```java
    @OnMessage
    public String onMessage(String message) {
        System.out.println("<< Server got message: " + message);
        String response = someLogic(message);     
        return response;        
    }
```

**Comment by AlexRomanch** [comment] 2015-12-24 10:28
Well, i found the reason of this trouble.
The reason is Kaspersky Anti-virus - when i turn off him, server received all message from client, without any problem.
How can i solve this? Make a special settings for Kaspersky on each client PC - i dont think this is a good idea.

**Comment by douglasjunior** [comment] 2015-12-24 13:31
Try different connection ports. Maybe there is a range of ports that antivirus permits.

**Comment by bendem** [comment] 2015-12-24 13:31
> In my project i use TooTallNate Websocket client in Java applet

"Java applet", there is your problem.

**Comment by marci4** [comment] 2017-04-15 21:36
Issue was caused by kaspersky :(

Closing issue.
Greetings
marci4

**Closed by marci4** 2017-04-15 21:36 UTC
Labels: Client
