### ISSUE TITLE
The onstart method of the WebSocketServer class sometimes fails to listen to the callback

### ISSUE THREAD

**Issue by lickKing9527** [TooTallNate/Java-WebSocket#1263] opened 2022-07-20 08:03 UTC
**Describe the bug**

I wrote a class that inherits WebSocketServer. After I call the start method, sometimes the callback cannot be monitored in the onstart method. This problem only occurs occasionally on Macs with 8GB of RAM. I don't know if it has anything to do with computer performance。

**To Reproduce**
1. Write a class MyWebSocketServer that inherits WebSocketServer.
2. Construct an instance of this class.
3. Create a websocket server.
4. Call the start method of WebSocketServer.
5. Strangely, for the same code, most of the time the callback can be monitored in the onstart method, but occasionally it cannot be monitored

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.

**Expected behavior**

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.

**Environment(please complete the following information):**
 - Version used: 1.5.1
 - Java version: jdk11
 - Operating System and version:macOS Monterey Version 12.4（CPU 3GHz，six cores intel Core I5；RAM 8GB 2667 MHz DDR4）
 - Endpoint Name and version:
 - Link to your project:

**Additional context**

**Comment by lickKing9527** [comment] 2022-07-22 09:45
> Please provide clear Steps to repeat (Example application to reproduce the issue)
Application is very simple。

public class MyMain {
      public static void main(String[] args) {
            MyWebSocketSev myWeb = new MyWebSocketSev("127.0.0.1",30000);
            myWeb.start();
      }
}

public class MyWebSocketSev extends WebSocketServer {
     public MyWebSocketSev (String hostname,String port) {
           super(new InetSocketAddress(hostname,Integer.valueOf(port)));
     }
    @Override
	public void onStart() {
		System.out.println("server started successfully");
	}
      .
      .
      .
      .
      .
      .
}


For the same code, most of the time the callback can be monitored in the onstart method, but occasionally it cannot be monitored.

**Comment by PhilipRoman** [comment] 2022-07-23 10:14
I ran the test 1000 times on each machine, could not reproduce.
Are you sure you are not closing the server before it has a chance to start?

```
Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 GNU/Linux
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)
```
```
Linux 5.15.43-0-virt #1-Alpine SMP Thu, 26 May 2022 10:32:47 +0000 Linux
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-alpine-r2)
OpenJDK 64-Bit Server VM (build 17.0.3+7-alpine-r2, mixed mode, sharing)
```
```
MSYS_NT-10.0 2.9.0(0.318/5/3) 2017-10-05 15:05 Msys
openjdk 11.0.2 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+7, mixed mode)
```

**Comment by lickKing9527** [comment] 2022-07-25 02:47
I am sure.
And I'm also very strange about this, on all windows and some macOS, the problem is not present. Only on this mac computer, the problem occurs occasionally. I don't know if it has something to do with system resources or the environment.

The operating environment in which the problem occurs：
JDK：
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment JBR-11.0.13.7-1751.21-dcevm (build 11.0.13+7-b1751.21)
Dynamic Code Evolution 64-Bit Server VM JBR-11.0.13.7-1751.21-dcevm (build 11.0.13+7-b1751.21, mixed mode)

Operating System and version:
macOS Monterey Version 12.4（CPU 3GHz，six cores intel Core I5；RAM 8GB 2667 MHz DDR4）

**Comment by marci4** [comment] 2022-10-18 05:15
Since we cannot reproduce this issue, I will close it until there is a better way to reproduce it.

**Closed by marci4** 2022-10-18 05:15 UTC
Labels: missing-information, cannot-reproduce
