### ISSUE TITLE
Can't connect to WebSocket Server when i'm using SSL

### ISSUE THREAD

**Issue by Dayssam** [TooTallNate/Java-WebSocket#536] opened 2017-08-11 13:45 UTC
Hi Everyone,

I want to connect to WebSocket Server with SSL, but no success (without ssl , its  working like a charm)

i'm using  the websocket in my webstart to communicate with the browser (Web App)

when i'm using https in my web app , i couldnt connect to my webstart through websocket (**WS**) in **IE** (Security Error)

So, i have to use secure WebSocket Server (**WSS**) to make the communication possible, i created my jks & i started the server but no successful connection when i'm using **wss://127.0.0.1**

For Information : i created my jks using this cmd : 

> keytool -genkey -validity 3650 -keystore keystore.jks -storepass sofi92 -keypass sofisoft -alias WSCertif -dname "CN=127.0.0.1, OU=XXXXXX, O=XXXXX, L=XXXX, S=XXXXX, C=XXXXXX

Any idea ?

**Comment by marci4** [comment] 2017-08-11 15:16
Hello @Dayssam,

you have to trust your self signed certificate.
This is kind of difficult to do on IE/Edge.
Try to export your certificate and trust it trough the certificate process.

Apart from this, please try your web app in other browser like chrome, you maybe need to generate a certificate with a different algorithm.

Greetings
marci4

**Comment by Dayssam** [comment] 2017-08-15 09:22
Thanks @marci4 for your time,

For information, when i'm not using a **secure web socket** in **HTTPS**, it's not working just in Internet Explorer.

It gives me 

> Security Error

**Comment by marci4** [comment] 2017-08-15 16:32
Hello @Dayssam,

I know, this behavior is the same on all browsers that all of the content has to be using https.

I never actually managed to get my self signed certificate trusted for wss just for https. I stopped after like 4 hours and gave up. It works with a offical signed certificate so I use an other browser for my testing.

Greetings
marci4

**Comment by Dayssam** [comment] 2017-08-18 17:51
hi @marci4  

Thanks for your time, i could trust a self signed certificate and make my webapp communicate with the websocket server  using chrome (Not IE) when i'm using Eclipse IDE.

In my case i want to use the websocket server it in a WebStart,App, but it gives me an error 

> java.io.FileNotFoundException: http:\192.168.1.31:8094\webApp\resources\jws\xxxajws.jar!\resource\key.jks (La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(Unknown Source)
> 	at java.io.FileInputStream.<init>(Unknown Source)
> 	at ma.xxxxxx.xxxxna.yyyyJWS.getSSLConextFromKeystore(Xxxxx.java:652)

**Comment by marci4** [comment] 2017-08-20 16:19
Hello @Dayssam,

the problem is that your keystore is not at the path where you say it is.

Probably just because of deployment, I quess. I have no idea who you structure your webapp so I can't help you there much.. sorry :(


Greetings
marci4

**Comment by marci4** [comment] 2017-08-24 11:01
Hello @Dayssam,

I also found this. Maybe it helps you.
https://github.com/qzind/tray/issues/6

Greetings
marci4

**Comment by Dayssam** [comment] 2017-08-24 19:17
Hi @marci4 

My problems are solved now
for this  [issue ](https://github.com/TooTallNate/Java-WebSocket/issues/536#issuecomment-323418904) 

i used Thread.currentThread().getContextClassLoader() to get My file.

for the first one its solved now .. #540

**Comment by marci4** [comment] 2017-08-25 17:47
Hello @Dayssam,

closing this issue then!

Greetings
marci4

**Closed by marci4** 2017-08-25 17:47 UTC
Labels: Info

**Comment by dhayananda** [comment] 2019-05-07 07:28
> Hi @marci4
> 
> My problems are solved now
> for this [issue ](https://github.com/TooTallNate/Java-WebSocket/issues/536#issuecomment-323418904)
> 
> i used Thread.currentThread().getContextClassLoader() to get My file.
> 
> for the first one its solved now .. #540

Hello @Dayssam,


I am struggling with websocket connection issue with SSL.
When I tried to check with command : # wscat -s echo -c wss://ip address:port
"error: self signed certificate"
facing above issue. can u help on same


Regards,
nanda6

**Comment by maiph** [comment] 2019-05-07 08:01
Hey @dhayananda, did you create the certificate yourself? Self signed certificates need to be added to the trusted root store

**Comment by dhayananda** [comment] 2019-05-07 08:51
> Hey @dhayananda, did you create the certificate yourself? Self signed certificates need to be added to the trusted root store

Thanks for your reply.
 I done openssl. can you explain me about "SSL need to be added to the trusted root".

**Comment by maiph** [comment] 2019-05-07 10:29
You need to add the certificate you created to the KeyStore used by your application.
I found [this article](https://medium.com/@codebyamir/the-java-developers-guide-to-ssl-certificates-b78142b3a0fc) if you want to learn more about it

**Comment by dhayananda** [comment] 2019-05-07 11:27
yes. That part i have done.
Is anything left with respect to same, which i need to look?

**Comment by maiph** [comment] 2019-05-07 12:32
Then thats probably an issue with `wscat`. Try creating a sample client for testing the connection.

**Comment by dhayananda** [comment] 2019-05-07 13:41
ok.
Is there anything you want to make sure regarding webserver(nginx) config file.

thank you
