### ISSUE TITLE
Not working onClose and onError

### ISSUE THREAD

**Issue by sakuraso13** [TooTallNate/Java-WebSocket#919] opened 2019-07-15 04:59 UTC
I use the okhttp library on the android client and when the user disconnects from the Internet onError or onClose does not occur on the server, tried to use your client library but the problem is the same. A bug or I just do not know something? Help me please. thank

**Comment by PhilipRoman** [comment] 2019-07-15 05:01
Possible duplicate of #900

**Comment by marci4** [comment] 2019-07-15 07:41
Hello @sakuraso13,

to identify this as a duplicate please provide additional steps to repeat!

Best regards,
Marcel

**Comment by NoahAndrews** [comment] 2019-07-15 13:50
@sakuraso13 You can also test pull request #914, which is intended to fix #900 by either building that branch from source, or using [this precompiled jar file](https://drive.google.com/file/d/1utw3r7h3-HKzmEJdE8rMHLP6dGqT3HJY/view?usp=sharing).

**Comment by PhilipRoman** [comment] 2019-08-16 08:23
No steps to reproduce provided. Closing dead issue.

**Closed by PhilipRoman** 2019-08-16 08:23 UTC
Labels: missing-information
