### ISSUE TITLE
reconnect() NullPointerException

### ISSUE THREAD

**Issue by 0xZhangKe** [TooTallNate/Java-WebSocket#745] opened 2018-08-02 02:15 UTC
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Thread.getId()' on a null object reference
	at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:269)
	at org.java_websocket.client.WebSocketClient.reconnect(WebSocketClient.java:222)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.connect(WebSocketThread.java:172)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.handleMessage(WebSocketThread.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:232)
	at com.xx.websocket.WebSocketThread.run(WebSocketThread.java:60)

**Comment by 0xZhangKe** [comment] 2018-08-02 02:33
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.start()' on a null object reference
	at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:270)
	at org.java_websocket.client.WebSocketClient.reconnect(WebSocketClient.java:222)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.connect(WebSocketThread.java:172)
	at com.xx.websocket.WebSocketThread$WebSocketHandler.handleMessage(WebSocketThread.java:93)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:232)
	at com.xx.websocket.WebSocketThread.run(WebSocketThread.java:60)

**Comment by PhilipRoman** [comment] 2018-08-02 05:26
Thanks for catching this error! It would be nice if you could add additional information to match the [issue template](https://github.com/TooTallNate/Java-WebSocket/blob/master/.github/ISSUE_TEMPLATE.md), especially the steps to reproduce and android/java version to make it easier to solve this issue.

**Comment by 0xZhangKe** [comment] 2018-08-02 06:14
Model：Meizu MX6 and OPPO A83T；
System version：Android 7.1.1
Java-WebSocke versiont：1.3.8

I don't know the steps，It`s from  Umeng  analytics. 
Maybe it's because reconnect() calls many times.

**Comment by PhilipRoman** [comment] 2018-08-02 06:24
By the way, are you sure that only one thread accesses the WebSocketClient object and calls connect/reconnect? It could be a race condition where the socket is reset while being connected.

**Comment by 0xZhangKe** [comment] 2018-08-02 06:51
@PhilipRoman Yes, only one thread .

**Comment by marci4** [comment] 2018-08-10 12:27
Any update?

**Comment by 0xZhangKe** [comment] 2018-08-13 06:56
Sorry,I have never recovered this bug.

**Comment by marci4** [comment] 2018-08-14 17:05
No steps to repeat! No template! And cannot reproduce by reporter....

Closing issue!
Best regards,
marci4

**Closed by marci4** 2018-08-14 17:05 UTC
Labels: Unclear, missing-template
