### ISSUE TITLE
WebSocket disconnects after sending ~1000 messages?

### ISSUE THREAD

**Issue by MatthewTGM** [TooTallNate/Java-WebSocket#1159] opened 2021-06-24 09:35 UTC
**Describe the bug**
My application sends ~10-50 packets per second, and my websocket will randomly close with the error code 1006 and no reason.

**To Reproduce**
1. Simply send messages.

**Example application to reproduce the issue**
https://gist.github.com/MatthewTGM/3d0568b51106a1689f185ff651264ccc

**Expected behavior**
Successful packet sending and receiving.

**Debug log**
```
[00:13:45] [WebSocketWriteThread-464/WARN] [TGMLib (TGMLibSocket)/]: Connection to socket was closed! (1006 | )
[00:13:45] [WebSocketWriteThread-464/ERROR] [TGMLib (TGMLibSocket)/]: An unexpected error occurred!
java.lang.IllegalStateException: WebSocketClient objects are not reuseable
	at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:354) ~[WebSocketClient.class:?]
	at xyz.matthewtgm.lib.socket.TGMLibSocket.connect(TGMLibSocket.java:54) ~[TGMLibSocket.class:?]
	at xyz.matthewtgm.lib.socket.TGMLibSocket.reconnect(TGMLibSocket.java:82) ~[TGMLibSocket.class:?]
	at xyz.matthewtgm.lib.socket.TGMLibSocket.onClose(TGMLibSocket.java:68) [TGMLibSocket.class:?]
	at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:619) [WebSocketClient.class:?]
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:522) [WebSocketImpl.class:?]
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:534) [WebSocketImpl.class:?]
	at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:583) [WebSocketImpl.class:?]
	at org.java_websocket.client.WebSocketClient.handleIOException(WebSocketClient.java:924) [WebSocketClient.class:?]
	at org.java_websocket.client.WebSocketClient.access$000(WebSocketClient.java:67) [WebSocketClient.class:?]
	at org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:753) [WebSocketClient$WebsocketWriteThread.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181-1-redhat]
```

**Environment(please complete the following information):**
 - Version used: 1.5.1
 - Java version: 1.8
 - Operating System and version: Windows 10
 - Endpoint Name and version: 
 - Link to your project: https://github.com/TGMDevelopment/TGMLib

**Additional context**
N/A

**Comment by PhilipRoman** [comment] 2021-06-24 15:08
You're not supposed to call `connect()` again on the same socket object. Your `reconnect()` method simply calls `connect()` which causes the issue. Use `reconnect()` instead: https://www.javadoc.io/static/org.java-websocket/Java-WebSocket/1.5.2/org/java_websocket/client/WebSocketClient.html#reconnect--

**Comment by PhilipRoman** [comment] 2021-06-24 15:45
I cannot reproduce. In your example, all the messages get sent and there is no error. Can you try adding slf4j-simple to path, set the logging level to trace and then see what happens right before disconnecting?

**Comment by MatthewTGM** [comment] 2021-06-24 20:58
> I cannot reproduce. In your example, all the messages get sent and there is no error. Can you try adding slf4j-simple to path, set the logging level to trace and then see what happens right before disconnecting?
> 
> Also, your reconnect method should call `reconnect()` instead of `connect()`, which would prevent the exception that you're seeing.

I changed it to use reconnect and I made more checks for whether or not it's connecting to the socket or isn't connected, but it still disconnects after too many messages. I have slf4j to the path and I checked with trace, but there was no additional information

**Comment by marci4** [comment] 2021-08-10 18:31
Was also not able to reproduce the issue.
Closing it!

Best regards,
Marcel

**Closed by marci4** 2021-08-10 18:31 UTC
Labels: cannot-reproduce
