### ISSUE TITLE
Connection reset error 1006

### ISSUE THREAD

**Issue by tretonis** [TooTallNate/Java-WebSocket#876] opened 2019-04-09 13:35 UTC
**Describe the bug**

**To Reproduce**
1. .
2. ..
3. ...
4. ....

**Example application to reproduce the issue**
A link to a github project/gist to reproduce the issue.

**Expected behavior**

**Debug log**
The the debug log (set the log level to `TRACE`) to help explain your problem.

**Environment(please complete the following information):**
 - Version used:
 - Java version:
 - Operating System and version:
 - Endpoint Name and version:
 - Link to your project:

**Additional context**

**Comment by marci4** [comment] 2019-04-09 20:36
Cannot reproduce!

**Comment by tretonis** [comment] 2019-04-09 22:52
This error also appears, but with a lower frequency.
But, I can not reproduce this error, it is random.

**Comment by tretonis** [comment] 2019-04-09 22:53
display error 1001 and 1006

**Comment by marci4** [comment] 2019-04-10 04:33
That "error" is caused by the server...

**Comment by tretonis** [comment] 2019-04-10 11:32
Thank you for sharing your time and your knowledge.

**Comment by marci4** [comment] 2019-04-10 15:03
Check out https://static.javadoc.io/org.java-websocket/Java-WebSocket/1.4.0/org/java_websocket/framing/CloseFrame.html#ABNORMAL_CLOSE and https://static.javadoc.io/org.java-websocket/Java-WebSocket/1.4.0/org/java_websocket/framing/CloseFrame.html#GOING_AWAY for some explanation

**Comment by marci4** [comment] 2019-04-19 14:16
Is this issue solved?

**Comment by tretonis** [comment] 2019-05-12 13:44
no, the problem continue

**Comment by marci4** [comment] 2019-05-12 14:03
Well then please provide better steps to repeat since I was not able to reproduce it with these small str.

Best regards,
Marcel

**Comment by marci4** [comment] 2019-05-20 17:35
@tretonis please provide better steps to repeat otherwhise I will close this issue again as cannot reproduce!

**Comment by tretonis** [comment] 2019-05-20 20:58
I'm sorry, this error does not have a logical sequence to happen. My program is connected to api from binary.com, and abruptly it disconnects. As I said, I greatly appreciate your esteemed collaboration for attention in sharing your time and your knowledge.

**Comment by marci4** [comment] 2019-05-24 18:02
As indicated by the close codes the issue looks to be server side.

Judging from the codes, the websocket client is behaving correctly.

Closing this issue as therefore not relevant!

Best regards,
Marcel

**Closed by marci4** 2019-05-24 18:02 UTC
Labels: cannot-reproduce, missing-information

**Comment by yippeesoft** [comment] 2019-07-04 07:56
no.
my server is extends  WebSocketServer.
client is WebSocketClient.

onClose 1006
