### ISSUE TITLE
support subProtocol?

### ISSUE THREAD

**Issue by jwilljacob** [TooTallNate/Java-WebSocket#311] opened 2015-04-29 09:36 UTC
Does it support subProtocol，How to use it?

**Comment by xzhanglc** [comment] 2015-04-29 09:49
can i use the constructor below to set header Sec-WebSocket-Protocol ?
 ```java
public WebSocketClient( URI serverUri , Draft protocolDraft , Map<String,String> httpHeaders , int connectTimeout )
```

**Comment by Computician** [comment] 2015-07-13 21:28
Knowing exactly how to do this would be helpful as I am running into an issue right now where I need to set the subprotocol and it is failing to do so. Any pointers on how to do this?

**Comment by dbrgn** [comment] 2016-06-21 07:45
Probably a duplicate of #253.

**Comment by dbrgn** [comment] 2016-06-21 08:01
> can i use the constructor below to set header Sec-WebSocket-Protocol ?

Thanks for the idea, this seems to work.

```java
Map<String, String> headers = new HashMap<>();
headers.put("Sec-WebSocket-Protocol", "super-duper-subproto-1.0");
WebSocketClient(serverUri, new Draft_17(), headers, connectTimeout);
```

**Comment by marci4** [comment] 2017-03-26 20:11
Hello @jwilljacob and @dbrgn,

I added an example to the wiki how you can add your custom Sec-Websocket-Protocol.
Check it out [here](https://github.com/TooTallNate/Java-WebSocket/wiki/Implementing-your-own-Sec-WebSocket-Protocol).

Greetings
marci4

**Closed** 2017-03-26 20:25 UTC

**Comment by farhanlatheef** [comment] 2018-05-08 07:25
@marci4 there is nothing in that link.

**Comment by Librichard** [comment] 2018-08-17 16:25
@farhanlatheef: I found it:
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SecWebSocketProtocolClientExample.java
