### ISSUE TITLE
WebSocketServer freezes in stop() method

### ISSUE THREAD

**Issue by vcucek** [TooTallNate/Java-WebSocket#259] opened 2014-05-12 09:42 UTC
Hello,

first I would like to thank you for creating a great and useful library.

I'am using it in Android application to communicate with website. 
When I try to stop the server, the application sometimes stops responding.
The main thread is indefinitely waiting in "WebSocketServer.stop()" method in "selectorThread.join()" line, because the "selectorThread" never ends. This happens because "selectorThread" is waiting in "run()" method in "selector.select()" line.

Do you know what could be the cause of this behavior?

Thank you all in advance for any help you can provide.

Regards,
Vito

**Comment by bendem** [comment] 2015-08-05 18:11
This happens on real java applications as well.

As described [here](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/Selector.html#select--), [this select call](https://github.com/TooTallNate/Java-WebSocket/blob/ac45d846806ad662de48c206896d1248acbb53ff/src/main/java/org/java_websocket/server/WebSocketServer.java#L296) is blocking. Thus, if stopping with a timeout of 0 (indefinite), [this line](https://github.com/TooTallNate/Java-WebSocket/blob/ac45d846806ad662de48c206896d1248acbb53ff/src/main/java/org/java_websocket/server/WebSocketServer.java#L226) will never be executed and the line before will hang forever. The thread should be interrupted in all cases.

In the meantime, using `stop(1)` fixes the problem (the first join will fail, the thread will be interrupted, the second join will wait for the thread).

**Comment by BrushfireDigitalServices** [comment] 2015-08-05 22:44
I have added this to the Complete Documentation milestone and will add the solution(s) to the new docs. To summarize, the key points to avoid this pitfall are as follows:

- To prevent stop() from blocking forever in some situations, use a positive timeout like stop(1) as @bendem suggests. 

- If developing for pre-Honeycomb Android, @vcucek links to an Android issue describing a separate bug where an [interrupt does not prevent blocking](https://code.google.com/p/android/issues/detail?id=15388) in some situations. The workaround is to "use Selector.wakeup(), possible[sic] in conjunction with Thread.interrupt()."

**Comment by bendem** [comment] 2015-08-06 16:32
Well, what I provided is a workaround to a bug. Calling stop() or stop(0) will never work if there are open connections because the selectorThread is joined before being interrupted so it's hanging forever on a select() call.

I'd rather see the bug fixed instead of documented.

**Closed** 2015-08-08 01:15 UTC
Labels: Android, Bug, Info, Server

**Comment by BrushfireDigitalServices** [comment] 2015-08-08 02:40
This should be fixed now that #329 is merged. @bendem contributed the fix and confirmed that it works on JDK 8. Since neither of us is an Android developer, it is still untested on Android.
