### ISSUE TITLE
rabbitmq message broker heartbeat frame problem

### ISSUE THREAD

**Issue by JeremyJT** [TooTallNate/Java-WebSocket#592] opened 2017-10-26 23:05 UTC
When we use stomp over websocket, the heartbeat frame's opcode is 1 instead of 0x9 or 0xA.
## Expected Behavior

The heartbeat frame's opcode should be 0x9 or 0xA.
## Debug log (for bugs)

The log from RabbitMQ:

STOMP detected missed client hearbeat(s) on connection 127.0.0.1:43352 -> 127.0.0.1:61613, closing it
## Your Environment

* Version used: 1.3.5
* Java version: 1.8
* Operating System and version: Android API 19
* Endpoint Name and version: RabbitMQ 3.6.10
* Link to your project:

**Comment by marci4** [comment] 2017-10-29 16:12
Hello @JeremyJT,

you are not using the Java-Websocket project directly, am I understanding you there correctly? 
If that is the case, please open a separate issue there!

Greetings
marci4

**Comment by marci4** [comment] 2017-11-02 20:12
Duplicate of NaikSoftware/StompProtocolAndroid/issues/84

Closing issue!
Greetings
marci4

**Closed by marci4** 2017-11-02 20:12 UTC
Labels: Unclear, waiting-for-feedback
