### ISSUE TITLE
SSL Exception -> Port Close

### ISSUE THREAD

**Issue by pmarchesi** [TooTallNate/Java-WebSocket#249] opened 2014-03-21 03:29 UTC
Hi, 

Sorry by my english

I using the ClientServer and chat.html . Result Ok
I add ssl to ClientServer with a trusted certificated and i add in a chat.html wss:// Result OK
Now i try to connect to "ClientServer with ssl" with chat.html ws:// Result the server crash and close the port. (without disconnect the establish conections)

Exception:
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
    at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:171)
    at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:845)
    at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:758)
    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
    at org.java_websocket.SSLSocketChannel2.unwrap(SSLSocketChannel2.java:150)
    at org.java_websocket.SSLSocketChannel2.processHandshake(SSLSocketChannel2.java:123)
    at org.java_websocket.SSLSocketChannel2.<init>(SSLSocketChannel2.java:75)
    at org.java_websocket.server.DefaultSSLWebSocketServerFactory.wrapChannel(DefaultSSLWebSocketServerFactory.java:39)
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:317)
    at java.lang.Thread.run(Thread.java:744)
Connection closed because ofjavax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

Thanks

Pablo

**Comment by marci4** [comment] 2017-03-30 20:59
Hello @pmarchesi and @sklegg 

do you still have this issue with the latest version?
Can't reproduce it here right now!

Greetings
marci4

**Comment by marci4** [comment] 2017-09-06 14:18
No update for months.

Closing issue!
Greetings
marci4

**Closed by marci4** 2017-09-06 14:18 UTC
Labels: Server, waiting-for-feedback, works-for-me, wss
