### ISSUE TITLE
Port stays bound after calling `WebSocketServer.close`.

### ISSUE THREAD

**Issue by Dykam** [TooTallNate/Java-WebSocket#220] opened 2013-12-08 20:39 UTC
After calling `WebSocketServer.close`, when trying to start a new WebSocketServer on the same port,  `WebSocketServer.start` throws an exception:

```
an error occured on connection null:java.net.BindException: Address already in use: bind
```

**Comment by EasyTarget86** [comment] 2015-09-10 18:34
I found that I needed the code in [pull 273](https://github.com/TooTallNate/Java-WebSocket/pull/273)

**Comment by marci4** [comment] 2017-03-26 19:59
Issue should be fixed with merge #272 

Greetings
marci4

**Closed by marci4** 2017-03-26 19:59 UTC

**Comment by Arazjel** [comment] 2018-10-26 11:47
The issue is still present in Android

**Comment by marci4** [comment] 2018-10-26 12:13
@Arazjel please open a new bug report with steps to repeat and an example application!!

**Comment by Arazjel** [comment] 2018-11-20 13:55
@marci4 ok I found out what went wrong before I managed to find free time for the example application, so what was going on wrong. 
In WebSocketServer in 
```
	public WebSocketServer( InetSocketAddress address , int decodercount , List<Draft> drafts , Collection<WebSocket> connectionscontainer ) {
		if( address == null || decodercount < 1 || connectionscontainer == null ) {
			throw new IllegalArgumentException( "address and connectionscontainer must not be null and you need at least 1 decoder" );
		}

		if( drafts == null )
			this.drafts = Collections.emptyList();
		else
			this.drafts = drafts;

		this.address = address;
		this.connections = connectionscontainer;
		setTcpNoDelay(false);
		setReuseAddr(false);
		iqueue = new LinkedList<WebSocketImpl>();

		decoders = new ArrayList<WebSocketWorker>( decodercount );
		buffers = new LinkedBlockingQueue<ByteBuffer>();
		for( int i = 0 ; i < decodercount ; i++ ) {
			WebSocketWorker ex = new WebSocketWorker();
			decoders.add( ex );
			ex.start();
		}
	}

```

`setReuseAddr(false)` prevents a server from reusing the same address

**Comment by NoahAndrews** [comment] 2018-11-20 15:07
You can call `setReuseAddr(true)` in the constructor of your `WebSocketServer` child class.
