### ISSUE TITLE
after i call close() method, why the tcp connect do not  disconnected?

### ISSUE THREAD

**Issue by TangDynasty06** [TooTallNate/Java-WebSocket#1411] opened 2024-05-16 12:40 UTC
i use java-Websocket as a client to connect my data server。
when i want to disconnect from server,i call close() method(in WebSocketClient class)。
but i find the tcp connection don't disconnected。
java-Websocket version is 1.5.6
![image](https://github.com/TooTallNate/Java-WebSocket/assets/16315451/444c2a00-80a4-4bba-8e34-0e23539fbc30)

**Comment by PhilipRoman** [comment] 2024-05-17 20:36
Cannot reproduce this issue, for me TCP connection is closed as expected.
Please provide a small program which reproduces the issue

**Closed** 2024-05-22 21:18 UTC
Labels: cannot-reproduce
