### ISSUE TITLE
Crash on samsung device with android8.0

### ISSUE THREAD

**Issue by yummyChina** [TooTallNate/Java-WebSocket#1402] opened 2024-02-27 12:06 UTC
**Describe what you would like to know or do**
on the samsung  device with android8.0 ,ran as Client such as:

   clientSocket = new ClientSocket(uri,header);

app crash !

crash trace info:
java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'org.java_websocket.drafts.Draft_6455' appears in /data/user/0/com.xxx.xxx/.cache/classes2.dex)
	at org.java_websocket.drafts.Draft_6455.<init>(Draft_6455.java:247)
	at org.java_websocket.drafts.Draft_6455.copyInstance(Draft_6455.java:464)
	at org.java_websocket.WebSocketImpl.<init>(WebSocketImpl.java:216)
	at org.java_websocket.client.WebSocketClient.<init>(WebSocketClient.java:234)
	at org.java_websocket.client.WebSocketClient.<init>(WebSocketClient.java:199)
	at org.java_websocket.client.WebSocketClient.<init>(WebSocketClient.java:185)
	at xxxxw.ebsocket.ClientSocket.<init>(ClientSocket.java:24)
	at xxxx.websocket.ClientSocket.connect(ClientSocket.java:60)
	.....
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Describe the solution you'd considered**
how to resolve it ?

**Comment by PhilipRoman** [comment] 2024-02-27 14:39
Duplicate of https://github.com/TooTallNate/Java-WebSocket/issues/1353
This is bug in Android btw

**Closed by PhilipRoman** 2024-02-27 14:39 UTC
