### ISSUE TITLE
java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by hahaerle** [TooTallNate/Java-WebSocket#697] opened 2018-04-18 14:29 UTC
## Expected Behavior

java.lang.OutOfMemoryError
Could not allocate JNI Env
--
 java.lang.Thread.nativeCreate(Native Method)
 java.lang.Thread.start(Thread.java:729)
 org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:280)
 java.lang.Thread.run(Thread.java:760)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:org.java-websocket:Java-WebSocket:1.3.7
* Java version:1.8
* Operating System and version: Android 6.0~7.1.2
* Endpoint Name and version:
* Link to your project:

**Comment by marci4** [comment] 2018-04-18 15:37
Hello @hahaerle,

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md.

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by marci4** [comment] 2018-04-18 15:42
_Could be duplicate and cannot reproduce (see #664)_

**Comment by marci4** [comment] 2018-05-01 17:10
No feedback.

Closing issue!
Best regards,
marci4

**Closed by marci4** 2018-05-01 17:10 UTC
Labels: Android, Unclear, missing-template
