### ISSUE TITLE
1006R closure - disconnecting hundreds of users hourly

### ISSUE THREAD

**Issue by villain-bryan** [TooTallNate/Java-WebSocket#1214] opened 2022-01-20 19:43 UTC
**Describe what you would like to know or do**
Hundreds of our users are experiencing the disconnect every 1-2 hours and it is becoming painful that we haven't resolved it. We've deduced from reports that several users are hit with more disconnects than others. Geographical location hasn't seemed to matter much since people are disconnecting that live right next to the server, and, well, everyone eventually experiences this disconnect if they stay online long enough.

Each Client's onClose() is returning the following parameters: `code=1006, reason = "", remote=true` consistently. We don't have much to go on as to why this is happening.

**Describe the solution you'd considered**
A solution that prevents clients from abnormally disconnecting randomly.

**Additional context**
Both the Client and Server have `webSocket.setConnectionLostTimeout(0);`. The server is running on a large Upcloud VPS host. I experience disconnects on a small, private server as well.
- The clients are using a WSS routed through Cloudflare.
- Disconnected clients have confirmed 0% packet loss, monitored with WinMTR.
- Server is using Nginx, located in the Upcloud NYC data center running on Ubuntu 20.04.

**Comment by villain-bryan** [comment] 2022-01-21 17:55
More information:

The method `SocketChannelIOHelper.read(final ByteBuffer buf, WebSocketImpl ws, ByteChannel channel)` is failing. The boolean `read` is being set to `-1` via `int read = channel.read(buf);` and is calling `ws.eot();`

We added logging to confirm the above for the 1006R failures (and `ws.eot()` is called), triggering `WebSocketImpl.closeConnection(CloseFrame.ABNORMAL_CLOSE, true);`

No idea why this is happening.

**Comment by villain-bryan** [comment] 2022-01-23 15:36
Is it possible that a 3rd party is terminating these WebSockets to cause us seeing this 1006R? Such as our VPS provider, or Cloudflare?

**Comment by marci4** [comment] 2022-01-23 21:53
Well the bytechannel returns -1 with the read, when channel has reached end-of-stream (https://docs.oracle.com/javase/7/docs/api/java/nio/channels/ReadableByteChannel.html#read(java.nio.ByteBuffer)).

I never used the websockets behind Cloudflare, cannot give you any help there.

**Comment by 0-x-2-2** [comment] 2022-01-23 22:49
This is probably caused by Cloudflare terminating the connections while rebooting servers. You must make your web-socket code handle this situation to use Cloudflare for long-term sessions.

https://community.cloudflare.com/t/websocket-disconnections/128979
https://discord.com/developers/docs/topics/gateway#resuming

**Comment by villain-bryan** [comment] 2022-01-24 17:42
Thanks for these insights @marci4. I appreciate those links and will attempt to implement something like that.

The link @0-x-2-2 mentioned discusses the code 1001 Going Away disconnect. We do see 1001, however 1006 is much more common. Could these 1006s that we're often seeing actually be 1001s (or, cloudflare disconnects) that have "morphed" into 1006 due to end-of-stream possibilities in this library's read code? I'm theorizing a bit here, but I'm pretty sure I've seen a payload get partially "cut off" in its data (half of a JSON message literally chopped in half of what it is supposed to be in payload data), perhaps a connection was originally closing abruptly due to 1001, then this library internalized the read causing it to immediately spit out a 1006. Not sure if that is even possible, just a guess to explain why 1006?

**Comment by marci4** [comment] 2022-01-26 20:14
I am not sure and I have no way to reproduce it. 
Maybe you can enable the logging and we can see, if there is any interesting frame being sent before

**Comment by villain-bryan** [comment] 2022-02-14 21:35
> Cloudflare straight up just drops the connection without warning in my experience using an entirely different library.

Have any experience with a CDN that doesn't do that .. or less frequently? Maybe Amazon CloudFront?

**Comment by 0-x-2-2** [comment] 2022-02-14 23:15
You are supposed to write your application to handle this, no CDN will proxy WebSockets for you indefinitely.

**Comment by marci4** [comment] 2022-05-08 19:37
I think this question is related to a CDN and not much we can to as a library.

Closing this issue.

**Closed by marci4** 2022-05-08 19:37 UTC
Labels: Server, Unclear
