### ISSUE TITLE
Same byte arrays

### ISSUE THREAD

**Issue by Krizis112** [TooTallNate/Java-WebSocket#1277] opened 2022-10-03 19:42 UTC
Hello, me again, again the same question.
Issue: I'm trying to develop a client for a browser game, But something went wrong =(
Step 1. I'm instantiating a player client.
Step 2.  I send to the server when a signal about connecting a new player.
Step 3. I'm starting to read the messages sent by the server and find them quite strange compared to the browser version of the game, namely some of the byte arrays came almost the same.
Java response example;
```
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12079, 47, 12079, 47, 47]
[47, 14127, 47, 5935, 47, 12335, 47, 12335, 47, 47]
```
Javascript response example:
![image](https://user-images.githubusercontent.com/59326567/193663932-47eb7fab-96ea-4a4e-881a-c7d436a76ac1.png)
I converted the byte buffer to the short array type through this method 
```
	public short[] getPosition(ByteBuffer buffer) {
		short[] sa = new short[buffer.capacity() / 2];
		
		for(int i = 0; i < sa.length; i++) {
			ByteBuffer bb = ByteBuffer.allocate(2);
			bb.order(ByteOrder.LITTLE_ENDIAN);
			bb.put(buffer.get(2 * 1));
			bb.put(buffer.get(2 * i + 1));
			sa[i] = bb.getShort(0);
		}
		
		return sa;
	}
}
```
The data received from Java and Javascript is very different, although messages are received in the same amount. Please help me understand, thanks in advance for the answer.

**Comment by marci4** [comment] 2022-10-03 19:53
Duplicate of #1276

**Closed by marci4** 2022-10-03 19:53 UTC
Labels: Duplicate
