### ISSUE TITLE
websocket waits for response for multiple commands

### ISSUE THREAD

**Issue by sky9971** [TooTallNate/Java-WebSocket#760] opened 2018-08-29 11:28 UTC
## Expected Behavior
I would like to send requests to my webserver without waiting for response, because if I wait for response it slows down my queue. In order to speed up the requests I don't the webserver to listen to any incoming messages. My webserver is only returning 200 as a response code which is not needed by me.

## Current Behavior
Currently the requests are getting queued and my android client waits for responses. which is adding to the delay.

## Possible Solution
Is there a way to send requests to webserver without waiting for responses.

## Steps to Reproduce (for bugs)

1. Create a client for websocket and connect to webserver.
2. Send about 20-30 commands to server from client.
3. The client suffers delay beween the first and the 30th command.

## Debug log (for bugs)
N/A

## Context
 My client has a persistent connection with my webserver,  I want to be able to make ~10 requests per second to my webserver. Since the client is waiting for the response ,it is adding a big delay between my commands

## Your Environment
* Version used: 1.3.9
* Java version: 8
* Operating System and version: Android 7

https://github.com/marci4/AndroidJavaWebsocketExample/blob/master/app/src/main/java/de/marci4/websockettest/MainActivity.java

I followed the client example from this project to create client on my android application.

**Comment by marci4** [comment] 2018-08-29 12:03
Hello @sky

Please use the `Bug Report` template provided at https://raw.githubusercontent.com/TooTallNate/Java-WebSocket/master/.github/ISSUE_TEMPLATE.md. DO NOT forget to provide an example code!

Without a full bug report this will be closed.

Best regards,
marci4

**Comment by marci4** [comment] 2018-09-21 16:50
No issue template, no additional infos.

Closing this issue as cannot reproduce!

Best regards,
marci4

**Closed by marci4** 2018-09-21 16:50 UTC
Labels: Android, Unclear, missing-information
