### ISSUE TITLE
How to use WebSocketClient using Proxy Authenticate?

### ISSUE THREAD

**Issue by PhamHuyThien** [TooTallNate/Java-WebSocket#1179] opened 2021-09-15 15:07 UTC
I want to use WebSocketClient with Authenticate Proxy, 
I used this way and failed:
```java
WebSocketClient wss = new WebSocketClient(new URI("wss://...")){...};
wss.setProxy(new Proxy(Type.HTTP, new InetSocketAddress("host", 22222)));
String base64Passw = Base64.getEncoder().encodeToString("user:passwr".getBytes());
wss.addHeader("Proxy-Authorization", "Basic "+base64Passw);
wss.connect();
```
The return result is:
```
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling0(HttpURLConnection.java:2253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/java.net.HttpConnectSocketImpl.doTunneling(HttpConnectSocketImpl.java:208)
	at java.base/java.net.HttpConnectSocketImpl.doTunnel(HttpConnectSocketImpl.java:197)
	at java.base/java.net.HttpConnectSocketImpl$2.run(HttpConnectSocketImpl.java:177)
	at java.base/java.net.HttpConnectSocketImpl$2.run(HttpConnectSocketImpl.java:175)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/java.net.HttpConnectSocketImpl.privilegedDoTunnel(HttpConnectSocketImpl.java:174)
	at java.base/java.net.HttpConnectSocketImpl.connect(HttpConnectSocketImpl.java:121)
	at java.base/java.net.Socket.connect(Socket.java:645)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
please help me, thanks.

**Comment by marci4** [comment] 2021-11-01 08:28
Dead issue.
Closing it!

**Closed by marci4** 2021-11-01 08:28 UTC
Labels: Question

**Comment by lovesh-ap** [comment] 2024-06-21 17:00
I'm facing the same issue even when provided Authorization via default [Authenticator](https://docs.oracle.com/javase/7/docs/api/java/net/Authenticator.html)

> java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
> sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2154)
> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> java.lang.reflect.Method.invoke(Method.java:498)
> java.net.HttpConnectSocketImpl.doTunneling(HttpConnectSocketImpl.java:179)
> java.net.HttpConnectSocketImpl.doTunnel(HttpConnectSocketImpl.java:168)
> java.net.HttpConnectSocketImpl.access$200(HttpConnectSocketImpl.java:44)
> java.net.HttpConnectSocketImpl$2.run(HttpConnectSocketImpl.java:151)
> java.net.HttpConnectSocketImpl$2.run(HttpConnectSocketImpl.java:149)
> java.security.AccessController.doPrivileged(Native Method)
> java.net.HttpConnectSocketImpl.privilegedDoTunnel(HttpConnectSocketImpl.java:148)
> java.net.HttpConnectSocketImpl.connect(HttpConnectSocketImpl.java:111)
> java.net.Socket.connect(Socket.java:607)
> com.newrelic.agent.security.deps.org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:473)
> java.lang.Thread.run(Thread.java:750)

**Comment by PhilipRoman** [comment] 2024-06-22 07:55
@lovesh-ap Please provide the code you use for connecting, otherwise I cannot help.

**Comment by lovesh-ap** [comment] 2024-06-23 06:14
Hi @PhilipRoman , this is the sample code i'm using with version `org.java-websocket:Java-WebSocket:1.5.3`

>     //WSClient extends WebSocketClient
>     private WSClient(String uri) throws URISyntaxException {
>         super(new URI(uri), new Draft_6455(), null, (int) TimeUnit.SECONDS.toMillis(15));
>         this.setTcpNoDelay(true);
>         this.setConnectionLostTimeout(30);
>         //some headers here
>         Proxy proxy = proxyManager();
>         if(proxy != null) {
>             this.setProxy(proxy);
>         }
>         this.setSocketFactory(this.cmSslContext);
>         logger.log(LogLevel.INFO, String.format("Connecting to WS client %s", AgentConfig.getInstance().getConfig().getK2ServiceInfo().getValidatorServiceEndpointURL()), WSClient.class.getName());
>     }
> 
>     private static Proxy proxyManager() {
>         try {
>             String proxyHost = "some-host";
>             Integer proxyPort = 4669;
>             Proxy.Type proxyType = Proxy.Type.HTTP;
>             String proxyUser = "some-user";
>             String proxyPass = "some-pass";
> 
>             if (proxyHost == null || proxyPort == null) {
>                 return null;
>             }
> 
>             Proxy proxy = new Proxy(proxyType, new InetSocketAddress(proxyHost, proxyPort));
> 
>             if (proxyUser != null && proxyPass != null) {
>                 // This Sets the authenticator that will be used by
>                 // the networking code when a proxy or an HTTP server asks for authentication.
>                 // This can lead to potential leak of authentication info by the application itself.
>                 Authenticator.setDefault(new Authenticator() {
>                     @Override
>                     protected PasswordAuthentication getPasswordAuthentication() {
>                         return new PasswordAuthentication(proxyUser, proxyPass.toCharArray());
>                     }
>                 });
>                 logger.log(LogLevel.FINER, "Authenticated proxy using username and password", WSClient.class.getName());
>             }
>             logger.log(LogLevel.FINER, String.format("Proxy being used to connect with WSS %s", proxy), WSClient.class.getName());
>             return proxy;
>         } catch (Exception e) {
>             logger.log(LogLevel.SEVERE, String.format("Error creating proxy %s", e.getMessage()), WSClient.class.getName());
>             return null;
>         }
>     }

As part of logs i do get `Authenticated proxy using username and password`

**Comment by PhilipRoman** [comment] 2024-06-23 09:29
Thanks for the code, assuming your proxy is using http Basic Auth, the problem is most likely this:
Since Java 8u111,  basic auth for proxies is disabled by default, you need to set the property `jdk.http.auth.tunneling.disabledSchemes` to the empty string.
For example:
```java
System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");
```
Source: https://www.oracle.com/java/technologies/javase/8u111-relnotes.html

If after this your connection is still working, please send the HTTP response that the proxy replies with, you can capture it with wireshark using the filter "http".

**Comment by lovesh-ap** [comment] 2024-07-18 06:08
Thanks for the update, @PhilipRoman this worked for us in case of Proxy Scheme is HTTP, but it doesn't go through when scheme is HTTPS.
I'm not clear what should be value for `Proxy.Type proxyType` when scheme is HTTPS

**Comment by lovesh-ap** [comment] 2024-08-08 07:04
Hi, @PhilipRoman hope all is well, can I get some assistant on how to set Proxy when using scheme HTTPs.
My current code is exiting with error **connection reset** 

>         String proxyHost = "some-host";
>         Integer proxyPort = 4669;
>         Proxy.Type proxyType = Proxy.Type.HTTP;
>         String proxyUser = "some-user";
>         String proxyPass = "some-pass";
> 
>         if (proxyHost == null || proxyPort == null) {
>             return null;
>         }
> 
>         Proxy proxy = new Proxy(proxyType, new InetSocketAddress(proxyHost, proxyPort));

**Comment by PhilipRoman** [comment] 2024-08-08 21:10
I'm not sure what you mean by a HTTPS proxy (how would the proxy decrypt your requests?)
What is the proxy software you're using?
