### ISSUE TITLE
after JAR recompilation: Found class org.java_websocket.WebSocket, but interface was expected

### ISSUE THREAD

**Issue by max-mc2labs** [TooTallNate/Java-WebSocket#328] opened 2015-08-05 11:35 UTC
Hi,
1. tested the java_websockets.jar with AutobahnServerTest.java (and a basic webpage): works.
2. I want to try to recompile the .jar from sources. ant: ok
3. re-compile and re-run AutobahnServerTest.java:

No port specified. Defaulting to 5555
///////////Opened connection number1
RECEIVED: WebSocket rocksss
java.lang.IncompatibleClassChangeError: Found class org.java_websocket.WebSocket, but interface was expected
    at AutobahnServerTest.onMessage(AutobahnServerTest.java:48)
    at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:457)
    at org.java_websocket.WebSocketImpl.deliverMessage(WebSocketImpl.java:561)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:328)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:149)
    at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:593)
closed conn=org.java_websocket.WebSocketImpl@1371c0c

AutobahnServerTest.java:48 is simple:
conn.send( message );

why?! (WebSocket is the interface, what's wrong!? -- I did not changed anything yet)
[CentOS6.5 | jdk1.7]

**Comment by max-mc2labs** [comment] 2015-08-05 13:53
(btw: I want to patching the websockets's implementation simply to store the session_id of each connection in the respective WebSocket object to avoid using an hashmap to address the single sessions objects -- for example on each onMessage? needed for my software model, which implements an array of threads for the users session)

**Comment by BrushfireDigitalServices** [comment] 2015-08-05 19:52
Upon researching the error, I see that unexplained "found class when interface was expected" problems pop up when building or testing with a slightly different toolchain than the code was written for.

I recompiled the jar a few days ago without problems. I'll check this evening which versions of which tools I used--let's compare versions and see if we need to update pom.xml.

Additionally, our Autobahn tests haven't been updated in a while, so the problem may be there. @ThreaT has [proposed a different set of acceptance tests]( https://github.com/TooTallNate/Java-WebSocket/compare/master...ThreaT:master) written against the current state of this library. They may allow the build to complete, but do still require code review and bug fixing.

**Comment by max-mc2labs** [comment] 2015-08-06 01:34
> our Autobahn tests haven't been updated in a while, so the problem may be there.

AutobahnServerTest.java is terribly simple (onOpen, onMessage, onClose -not more), can't be the source of the issue.

conn.send( message );
calling the send method of conn, the WebSocket object: this throws the exception.

        public void onMessage( WebSocket conn, String message ) {
                System.out.println("RECEIVED: "+message);
                conn.send( message ); <--------- (?!)
                //conn.close(1000);
        }

**Comment by bendem** [comment] 2015-08-06 07:56
> java.lang.IncompatibleClassChangeError: Found class org.java_websocket.WebSocket, but interface was expected

The WebSocket class [was made an interface in 2013](https://github.com/TooTallNate/Java-WebSocket/commit/51ec156b25bf535dce2770af1d74713d74a5d155). How did you compile it from sources and get a version prior to that?

My guess is that the compilation process failed at some point and you're using the [version from 2012](https://github.com/TooTallNate/Java-WebSocket/commit/51ec156b25bf535dce2770af1d74713d74a5d155) which doesn't contain the interface.

**Comment by max-mc2labs** [comment] 2015-08-06 11:14
> The WebSocket class was made an interface in 2013. How did you compile it from sources 
> and get a version prior to that?

this is the stranger part of the issue for me: here the WebSocket object IS an interface, NOT a class.
(source files comes from here, they are not out-of-date: I got websocket sources cloning this TooTallNate git project about 1 week ago: here WebSocket object IS an interface).

this is why is completly I do not understand the exception.
just in the case I would except the contrary: found interface but class expected.
found class but interface expected is not coherent at my eyes. but it throws.

btw
il I use the original .jar file included in the git folder under ./dist, the one existing _before_ recompiling with ANT (I did a safe copy of that original .jar before doing the first ANT), everything works.
if I change back to the ant-recompiled .jar, the AutobahnServerTest.java fails as seen above.
nb of course I did not make any change yet.
ps of course I already did an rm -rf and then git clone again. no changes.

please note that I use only vi, java and javac. no maven.
as said: jdk1.7 on a CentOS6.5 server. not else.

**Comment by bendem** [comment] 2015-08-06 12:06
That's really weird. Can you open the jar you compiled with ant and check WebSocket is actually a class? How do you run the AutobahnServerTest example?

**Comment by max-mc2labs** [comment] 2015-08-06 12:42
1) from the 2 jar files:
javap on the original WebSocket.class file:
public abstract class org.java_websocket.WebSocket

javap on the recompiled WebSocket.class file:
public interface org.java_websocket.WebSocket

of course in both source WebSocket.java files the WebSocket declaration is:
public interface WebSocket

2) I run AutobahnServerTest simply with <java AutobahnServerTest.java> <g>

source file is simple and mostly unchanged:
http://www.mc2labs.net/others/issues/jws/AutobahnServerTest.java.txt

and the source file of the corrisponding client side:
http://www.mc2labs.net/others/issues/jws/test2.html.txt

**Comment by bendem** [comment] 2015-08-06 13:02
> 2) I run AutobahnServerTest simply with 'java AutobahnServerTest'

Where do you feed it the jar to get the implementation from? Can you try running is with `-cp /path/to/new.jar`?

**Comment by max-mc2labs** [comment] 2015-08-06 13:22
do you mean where are the jar files I use?
in /opt/jdk1.7.0_65/jre/lib/ext/ 

I have both jar files there:
java_websocket.jar.org
java_websocket.jar.new
(which with those extensions are obviously skipped)

then I cp to java_websocket.jar the jar I need to test and I recompile
no need of javac -cp /path/to/new.jar (if I understand well your question)

**Comment by BrushfireDigitalServices** [comment] 2015-08-06 18:09
Hi all, it looks like [this StackOverflow question](http://stackoverflow.com/questions/591411/java-error-found-interface-but-class-was-expected) might be talking about the same underlying situation as this "found class but interface was expected" error.

Specifically, the accepted answer states "this happens when your runtime classpath is different than your compile time classpath... This is a common occurence if you had a different version of a jar file on the compile time classpath than on the runtime classpath."

Does running `mvn clean` and/or changing tge runtime classpath help?

Other items I've found discussing the error sound like less similar situations, but a recurring theme is that under the wrong conditions, having an older jar on your compile time classpath is correlated with this error in the new jar at runtime.

**Comment by Nackloose** [comment] 2016-07-26 08:27
Experiencing this identical issue as of three days ago with no avail to my problem. Has anyone found a solution or any new pointers?

**Comment by marci4** [comment] 2017-04-03 07:06
Hello @max-mc2labs,

is this still an issue for you with the latest version of the lib?

Greetings
marci4

**Comment by max-mc2labs** [comment] 2017-04-03 14:12
Hi @marci4,

sorry but I gave up on the issue in Aug 2015, so I haven't tested the latest version of the lib.
Good luck.

max

**Comment by marci4** [comment] 2017-04-03 14:32
Since I cannot reproduce this issue and you gave up, I am gonna close this issue.

Greetings
marci4

**Closed by marci4** 2017-04-03 14:32 UTC
Labels: Bug, Unclear, waiting-for-feedback

**Comment by max-mc2labs** [comment] 2017-04-03 14:36
roger.
