### ISSUE TITLE
Find password (PEM) from Letsencrypt (SSL)

### ISSUE THREAD

**Issue by SossenSystems** [TooTallNate/Java-WebSocket#797] opened 2018-10-25 19:22 UTC
Hello, I have a question.
I have linked the WSS socket with a Lets Encrypt certificate, but I randomly enter a password (PEM).
This works, but the server often does not accept WSS client connections.
There will be no excaption or anything printed.
I've tested the public ECHO server times always takes the connection, only the server is not always (sometimes not even after many attempts).

The Client is running under javascript on web.

What can I do...
Thank you for the cool project, works fine in itself! :)

**Comment by marci4** [comment] 2018-10-28 18:18
Hello @SossenSystems,

I do not get what you mean when you say you have to enter a password.
I am running a production server with a let's encrypt certificate without any problems.

What do you mean by not accepting connections?
Is this issue present in any client or only in a specific one (e.g. firefox)?

Best regards,
marci4

**Comment by SossenSystems** [comment] 2018-10-28 22:06
Hey @marci4,
I apologize with the statement of the certificate, that has already been done. Since you have done everything right, good work!

My problem is that Firefox has problems connecting to the wss server, unfortunately I have to reload the page sometimes, sometimes even rebooting the server to connect the client to the server. I have often tested it with the public wss echo server which connects perfectly every time, so my guess is that the server often rejects connections.

I thank you for the feedback again :-)

**Comment by marci4** [comment] 2018-10-29 22:01
Hey @SossenSystems,

I was just wondering since I use the same exact code for production why it would not work for you ;)

Yeah there is a known issue that the current SSL implementation does not work well with firefox (and on buggy android version).
This however will be fixed (one day I hope...) by #717

Best regards,
marci4

**Comment by marci4** [comment] 2018-11-05 21:46
Hello @SossenSystems,
is this issue solved for you?
If so, please close this issue!

Best regards,
marci4

**Comment by SossenSystems** [comment] 2018-11-05 22:29
Hi @marci4,

the problem persists only with Firefox, funny enough the problem is only with the server like that :(

Best regards
Michael

**Comment by marci4** [comment] 2018-11-06 17:46
Hello @SossenSystems,

you would make me very happy if you got the time and fix this issue with a PR.

Best regards,
marci4

**Comment by marci4** [comment] 2018-12-23 17:47
Closing this issue since it is a duplicate and the question is answered.

Duplicate of #717 
Best regards,
Marcel

**Closed by marci4** 2018-12-23 17:47 UTC
Labels: Question
