### ISSUE TITLE
WebSocketServer should send a close frame to echo the client close frame

### ISSUE THREAD

**Issue by Josh-Larson** [TooTallNate/Java-WebSocket#887] opened 2019-05-02 03:41 UTC
According to the WebSocket RFC, an endpoint should respond with a close frame when it receives a close frame (when reasonable to do so).  This could be either default behavior or called manually by the server callback `onClose(WebSocket, int, String, boolean)`.

Currently, the call to `close()` is ignored in the callback.  As far as I can tell this is because the connection is no longer considered open.

**Comment by marci4** [comment] 2019-05-05 15:26
Hello @Josh-Larson,

We do send a close frame here. https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/WebSocketImpl.java#L458

All autobahn tests run without problems in this area!

Best regards,
Marcel

**Comment by marci4** [comment] 2019-06-12 20:07
No steps to repeat, cannot reproduce and therefore closing this issue!

Best regards,
Marcel

**Closed by marci4** 2019-06-12 20:07 UTC
Labels: cannot-reproduce, missing-information
